org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
forge_version=47.2.0
mod_id=seeking_immortals
mod_name=瀵讳粰闂亾
mod_license=All Rights Reserved
mod_version=0.1.500
mod_group_id=com.xunxian.seekingimmortals
mod_authors=YourName
mod_description=鍘熷垱鍑′汉娴佷慨浠欑帺娉曟ā缁勶細鐏靛姏銆佸鐣屻€佺伒鐭炽€佷腹鑽€佹硶瀹濄€佺绠撲笌鐏电煶鐭裤€?

geckolib_version=4.8.4
architectury_version=9.1.12
ftb_library_version=2001.2.9
ftb_teams_version=2001.3.0
ftb_quests_version=2001.4.22
