package com.xunxian.seekingimmortals.skill;

import com.xunxian.seekingimmortals.cultivation.Realm;
import com.xunxian.seekingimmortals.cultivation.RealmStage;
import com.xunxian.seekingimmortals.cultivation.SpiritualRootAttribute;

public enum SkillType {
    LAVA_BURST("\u7194\u5ca9\u7206", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "lava_burst", 14, 130, "\u706b\u571f\u7075\u529b\u7206\u88c2\u6210\u7194\u5ca9\u51b2\u51fb\u7684\u8303\u56f4\u672f", SpiritualRootAttribute.FIRE, SpiritualRootAttribute.EARTH),
    MIST_RAIN("\u96fe\u96e8\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "mist_rain", 8, 90, "\u5316\u6c34\u7075\u4e3a\u96fe\u96e8\u843d\u4e0b\u7684\u8303\u56f4\u672f", SpiritualRootAttribute.WATER),
    SAND_STORM("\u6c99\u66b4\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "sand_storm", 12, 120, "\u51dd\u571f\u5316\u6c99\u6270\u654c\u7684\u8303\u56f4\u672f", SpiritualRootAttribute.EARTH),
    BLIZZARD("\u66b4\u96ea\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "blizzard", 13, 140, "\u5bd2\u6c14\u6210\u96ea\u56f0\u654c\u7684\u51b0\u7cfb\u8303\u56f4\u672f", SpiritualRootAttribute.ICE, SpiritualRootAttribute.WATER),
    CYCLONE("\u65cb\u98ce\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cyclone", 10, 110, "\u98ce\u7075\u65cb\u5377\u7275\u5236\u76ee\u6807\u7684\u8303\u56f4\u672f", SpiritualRootAttribute.WIND),
    CHAIN_LIGHTNING("\u8fde\u9501\u96f7", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "chain_lightning", 17, 170, "\u7075\u96f7\u5728\u591a\u4e2a\u76ee\u6807\u95f4\u8df3\u8dc3\u7684\u8303\u56f4\u672f", SpiritualRootAttribute.THUNDER),
    FIVE_THUNDER("五雷正法", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_8, "five_thunder", 25, 220, "道门五雷成阵轰击范围目标，以自定义雷弧粒子表现", SpiritualRootAttribute.THUNDER, SpiritualRootAttribute.HIDDEN_THUNDER),
    PURE_YANG_SWORD("纯阳剑气", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "pure_yang_sword", 21, 160, "纯阳气化作金白剑芒贯穿前方目标", SpiritualRootAttribute.FIRE),
    TAOIST_SEAL("道家法印", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "taoist_seal", 14, 130, "道门法印镇压单体目标，显形并削弱其行动"),
    CLOUD_WALK("云游步", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "cloud_walk", 12, 150, "踏云借势提升身法并获得短暂缓坠", SpiritualRootAttribute.WIND),
    IMMORTAL_ROPE("捆仙绳术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "immortal_rope", 16, 150, "灵绳成束缚住单体目标并压制出手"),
    BAGUA_SEAL("八卦印", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_7, "bagua_seal", 22, 190, "八卦法印展开阵纹，镇压范围内目标"),
    DAO_NATURE_BREATH("自然吐纳", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "dao_nature_breath", 10, 140, "顺应自然吐纳回补灵力并平复走火风险", SpiritualRootAttribute.WOOD),
    ELEMENTAL_BURST_FIRE("火系爆发术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "elemental_burst_fire", 18, 150, "筑基火系爆发弹，灼伤并冲击目标", SpiritualRootAttribute.FIRE),
    ELEMENTAL_BURST_WATER("水系爆发术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "elemental_burst_water", 18, 150, "筑基水系爆发弹，迟滞并冲击目标", SpiritualRootAttribute.WATER),
    ELEMENTAL_BURST_EARTH("土系爆发术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "elemental_burst_earth", 18, 150, "筑基土系爆发弹，沉重压制目标", SpiritualRootAttribute.EARTH),
    ELEMENTAL_BURST_WIND("风系爆发术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "elemental_burst_wind", 18, 150, "筑基风系爆发弹，高速撕裂目标", SpiritualRootAttribute.WIND),
    ELEMENTAL_BURST_METAL("金系爆发术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "elemental_burst_metal", 18, 150, "筑基金系爆发弹，锐芒贯穿目标", SpiritualRootAttribute.METAL),
    ELEMENTAL_BURST_WOOD("木系爆发术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "elemental_burst_wood", 18, 150, "筑基木系爆发弹，藤劲缠滞目标", SpiritualRootAttribute.WOOD),
    ELEMENTAL_BURST_ICE("冰系爆发术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "elemental_burst_ice", 18, 150, "筑基冰系爆发弹，冻结并冲击目标", SpiritualRootAttribute.ICE),
    ELEMENTAL_BURST_THUNDER("雷系爆发术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "elemental_burst_thunder", 18, 150, "筑基雷系爆发弹，麻痹并震慑目标", SpiritualRootAttribute.THUNDER),
    ICE_SPEAR("冰矛术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "ice_spear", 18, 150, "筑基冰系凝矛术，锐寒穿刺并冻结目标", SpiritualRootAttribute.ICE, SpiritualRootAttribute.WATER),
    FLAME_BURST("炎爆术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "flame_burst", 18, 150, "筑基火系炎爆术，灵焰爆裂并波及近旁目标", SpiritualRootAttribute.FIRE),
    HUANGFENG_FIRE_SERPENT("黄枫火蛇术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "huangfeng_fire_serpent", 18, 150, "黄枫谷火蛇扑击，追势炽烈且灼伤目标", SpiritualRootAttribute.FIRE),
    LUOYUN_SPIRIT_FLAME("落云灵焰", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "luoyun_spirit_flame", 18, 150, "落云丹火化作灵焰束，灼烧直线目标", SpiritualRootAttribute.FIRE),
    ICE_JADE_SHIELD("冰玉盾", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "ice_jade_shield", 22, 180, "玄冰凝成玉盾，护身并偏折近处飞矢", SpiritualRootAttribute.ICE, SpiritualRootAttribute.WATER),
    WOOD_SPIRIT_VINE("木灵藤", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "wood_spirit_vine", 20, 160, "木灵藤萝缚足，迟滞并削弱单个目标", SpiritualRootAttribute.WOOD),
    WATER_MIRROR_REFLECT("水镜术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "water_mirror_reflect", 20, 180, "水镜护身，折返近处敌对飞矢与术法", SpiritualRootAttribute.WATER),
    HEAL_QI("\u56de\u6c14\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "heal_qi", 15, 120, "\u6728\u6c34\u7075\u529b\u56de\u8865\u6c14\u8109\uff0c\u6062\u590d\u81ea\u8eab\u7075\u529b\u5e76\u5fae\u7597\u4f24", SpiritualRootAttribute.WOOD, SpiritualRootAttribute.WATER),
    DETOXIFY("\u89e3\u6bd2\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "detoxify", 12, 110, "\u4ee5\u6728\u7075\u751f\u673a\u6d17\u53bb\u6bd2\u7634\u4e0e\u9634\u90aa\u72b6\u6001", SpiritualRootAttribute.WOOD),
    SPIRIT_RECOVERY("\u51dd\u795e\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "spirit_recovery", 12, 140, "\u51dd\u805a\u8bc6\u6d77\u6e05\u5149\uff0c\u6062\u590d\u795e\u8bc6\u5e76\u5e73\u590d\u8d70\u706b\u98ce\u9669"),
    BODY_REPAIR("\u7597\u4f24\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "body_repair", 20, 160, "\u6c34\u6728\u7075\u529b\u4fee\u590d\u8089\u8eab\u6697\u4f24", SpiritualRootAttribute.WOOD, SpiritualRootAttribute.WATER),
    GROUP_HEAL("\u7fa4\u4f53\u7597\u4f24", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_8, "group_heal", 25, 240, "\u5c06\u751f\u673a\u5316\u4f5c\u6cbb\u7597\u6ce2\u7eb9\uff0c\u56de\u590d\u8fd1\u8eab\u540c\u4f34", SpiritualRootAttribute.WOOD),
    REVIVE_WEAK("\u7eed\u547d\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "revive_weak", 12, 220, "\u4ee5\u7075\u5149\u62a4\u4f4f\u547d\u8109\uff0c\u5728\u5371\u6025\u65f6\u66f4\u5f3a\u529b\u56de\u590d", SpiritualRootAttribute.WOOD),
    SPIRIT_SHIELD("\u7075\u529b\u62a4\u7f69", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "spirit_shield", 10, 180, "\u7075\u529b\u6210\u7f69\u62a4\u8eab\uff0c\u504f\u6298\u8fd1\u8eab\u98de\u77e2"),
    TRIBULATION_THUNDER_WARD("\u62a4\u52ab\u96f7\u7f69", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "tribulation_thunder_ward", 34, 360, "\u4ee5\u96f7\u5149\u7f16\u6210\u62a4\u52ab\u6cd5\u7f69\uff0c\u77ed\u65f6\u6297\u8861\u52ab\u96f7", SpiritualRootAttribute.THUNDER),
    MIRROR_PHANTOM("\u955c\u5f71\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "mirror_phantom", 8, 100, "\u955c\u5f71\u6298\u5149\u6270\u4e71\u5355\u4f53\u76ee\u6807"),
    HUNDRED_ILLUSION("\u767e\u5e7b\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_7, "hundred_illusion", 17, 180, "\u767e\u91cd\u5e7b\u5f71\u6269\u6563\u6210\u5e7b\u57df\u6270\u654c"),
    MIND_CONFUSION("\u8ff7\u5fc3\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "mind_confusion", 9, 120, "\u4ee5\u5e7b\u5ff5\u6270\u4e71\u76ee\u6807\u5fc3\u795e"),
    VOID_STEP("\u865a\u6b65", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "void_step", 11, 120, "\u8e0f\u51fa\u865a\u5f71\u77ed\u8ddd\u79fb\u5f62\u5e76\u6270\u4e71\u8def\u5f84\u654c\u4eba"),
    DREAM_SNARE("\u68a6\u7f20", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "dream_snare", 13, 150, "\u5e7b\u68a6\u7ec6\u7ebf\u7f20\u4f4f\u76ee\u6807\u610f\u8bc6"),
    CLONE_IMAGE("\u5206\u8eab\u5e7b\u5f71", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "clone_image", 12, 180, "\u5728\u8eab\u5468\u7559\u4e0b\u591a\u91cd\u5047\u5f71\u8bf1\u654c"),
    VEIL_OF_MOON("\u6708\u7eb9\u969c", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "veil_of_moon", 20, 200, "\u6708\u534e\u5e7b\u7eb9\u9690\u53bb\u6c14\u606f\u5e76\u62a4\u8eab"),
    INVISIBILITY_BASIC("\u9690\u533f\u672f", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "invisibility_basic", 18, 220, "\u57fa\u7840\u9690\u533f\u6cd5\u672f\uff0c\u77ed\u65f6\u6de1\u53bb\u8eab\u5f62\u4e0e\u6c14\u606f"),
    ILLUSION_MIST("\u5e7b\u96fe\u672f", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "illusion_mist", 18, 180, "\u5e7b\u96fe\u7b3c\u7f69\u5468\u8eab\uff0c\u9690\u8eab\u5e76\u8ff7\u4e71\u8fd1\u654c"),
    INVERSE_STAR_VEIL("\u9006\u661f\u533f\u5f62", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.MIDDLE, "inverse_star_veil", 18, 220, "\u9006\u661f\u5e7b\u7eb9\u906e\u853d\u8eab\u5f62\u5e76\u6298\u6563\u8ffd\u8e2a"),
    YANYUE_MOON_ILLUSION("\u63a9\u6708\u5e7b\u8eab", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.MIDDLE, "yanyue_moon_illusion", 18, 220, "\u63a9\u6708\u5b97\u5e7b\u8eab\u6cd5\uff0c\u4ee5\u6708\u5f71\u8ff7\u654c\u800c\u9690\u8eab"),
    YANYUE_PHANTOM_ARRAY("\u63a9\u6708\u5e7b\u9635", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "yanyue_phantom_array", 38, 300, "\u63a9\u6708\u79d8\u5f0f\u5e7b\u9635\uff0c\u4ee5\u6708\u5f71\u73af\u9635\u9547\u538b\u6218\u573a"),
    WANHU_NINE_ILLUSION("\u4e5d\u5c3e\u5e7b\u5883", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "wanhu_nine_illusion", 26, 260, "\u4e07\u72d0\u79d8\u672f\u5c55\u5f00\u4e5d\u91cd\u5e7b\u5883\u4e71\u654c"),
    SOUL_DEVOURING_CLOUD("噬魂云", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "soul_devouring_cloud", 8, 180, "玄阴阴云噬魂蚀体，缓慢腐蚀范围内敌人", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    YIN_SOUL_CHAIN("阴魂链", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "yin_soul_chain", 14, 140, "阴魂锁链束缚单个目标并牵制其行动", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    UNDERWORLD_FLAME("幽冥火", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "underworld_flame", 19, 150, "幽冥阴火凝成魂焰射线灼伤前方目标", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    CORPSE_ARMOR("炼尸甲", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "corpse_armor", 12, 220, "玄阴尸气结成护甲，短暂提升防护", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    QINGYUAN_SWORD_RAY("\u9752\u5143\u5251\u8292", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "qingyuan_sword_ray", 22, 150, "\u9752\u5143\u5251\u8bc0\u51dd\u6210\u4e00\u7ebf\u5251\u8292\u8d2f\u7a7f\u654c\u4eba", SpiritualRootAttribute.METAL),
    FLYING_SWORD_STRIKE("\u5fa1\u5251\u65a9", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "flying_sword_strike", 19, 120, "\u4ee5\u98de\u5251\u51fa\u624b\u65a9\u654c\u7684\u7b51\u57fa\u5251\u672f", SpiritualRootAttribute.METAL),
    GREEN_BAMBOO_SWORD_QI("\u9752\u7af9\u5251\u6c14", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "green_bamboo_sword_qi", 20, 140, "\u9752\u7af9\u7075\u6c14\u5316\u4e3a\u6728\u5c5e\u5251\u6c14", SpiritualRootAttribute.WOOD, SpiritualRootAttribute.METAL),
    SWORD_SHIELD("\u5251\u76fe", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "sword_shield", 12, 180, "\u5251\u5149\u73af\u62a4\u5468\u8eab\u5e76\u504f\u6298\u98de\u77e2", SpiritualRootAttribute.METAL),
    SWORD_ESCAPE("\u5251\u9041", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "sword_escape", 15, 150, "\u8eab\u5316\u5251\u5149\u77ed\u8ddd\u7a7f\u884c\u5e76\u7559\u4e0b\u5251\u75d5", SpiritualRootAttribute.METAL),
    THOUSAND_SWORD_ARRAY("\u4e07\u5251\u9635", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.LATE, "thousand_sword_array", 40, 240, "\u5251\u5149\u6210\u9635\u843d\u4e0b\u5251\u96e8\u9547\u538b\u4e00\u7247\u6218\u573a", SpiritualRootAttribute.METAL),
    BLOOD_SWORD_SLASH("\u8840\u5f71\u5251\u65a9", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.MIDDLE, "blood_sword_slash", 25, 150, "\u8840\u5f71\u5251\u8292\u8fd1\u8eab\u6a2a\u65a9\u5e76\u4ee5\u5251\u610f\u56de\u6c14\u62a4\u8eab", SpiritualRootAttribute.METAL),
    SWORD_MERGE("\u4eba\u5251\u5408\u4e00", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.MIDDLE, "sword_merge", 12, 220, "\u4ee5\u98de\u5251\u4e3a\u5f15\u4e0e\u5251\u610f\u5408\u4e00\uff0c\u77ed\u6682\u589e\u5f3a\u8eab\u6cd5\u3001\u653b\u52bf\u4e0e\u9632\u62a4", SpiritualRootAttribute.METAL),
    INVISIBLE_SWORD("\u65e0\u5f62\u5251", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.LATE, "invisible_sword", 26, 160, "\u51dd\u6210\u96be\u4ee5\u5bdf\u89c9\u7684\u900f\u660e\u5251\u8292\u7a7f\u523a\u76ee\u6807", SpiritualRootAttribute.METAL),
    SWORD_DOMAIN("\u5251\u57df", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.LATE, "sword_domain", 35, 260, "\u5c55\u5f00\u5251\u610f\u9886\u57df\uff0c\u4ee5\u73af\u7ed5\u5251\u75d5\u538b\u5236\u5468\u8eab\u654c\u4eba", SpiritualRootAttribute.METAL),
    DUAL_SWORD_DANCE("\u53cc\u5251\u821e", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.MIDDLE, "dual_sword_dance", 24, 130, "\u53cc\u5251\u4ea4\u9519\u821e\u51fa\u5341\u5b57\u5251\u75d5\u65a9\u51fb\u524d\u65b9", SpiritualRootAttribute.METAL),
    PRIMORDIAL_MAGNET_SPHERE("\u5143\u78c1\u795e\u5149", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "primordial_magnet_sphere", 26, 220, "\u5143\u78c1\u4e4b\u529b\u6444\u7269\u63a7\u654c\uff0c\u7275\u5236\u98de\u77e2\u4e0e\u8fd1\u8eab\u654c\u4eba", SpiritualRootAttribute.METAL),
    FLAME_SERPENT_STORM("\u708e\u86c7\u98ce\u66b4", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "flame_serpent_storm", 30, 220, "\u706b\u86c7\u4ea4\u7ec7\u6210\u98ce\u66b4\uff0c\u4ee5\u81ea\u5b9a\u4e49\u7075\u7130\u8f68\u8ff9\u707c\u4f24\u7fa4\u654c", SpiritualRootAttribute.FIRE),
    EARTH_MOUNTAIN_PRESS("\u5c71\u5cb3\u538b", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "earth_mountain_press", 28, 210, "\u571f\u7075\u5316\u5c71\u5f71\u7838\u843d\uff0c\u538b\u5236\u8303\u56f4\u5185\u76ee\u6807", SpiritualRootAttribute.EARTH),
    XUANTIAN_ICE_PRISON("\u7384\u5929\u51b0\u7262", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "xuantian_ice_prison", 30, 240, "\u7384\u51b0\u6210\u7262\u5c01\u7981\u884c\u52a8\uff0c\u4ee5\u51b0\u6676\u7c92\u5b50\u56f0\u654c", SpiritualRootAttribute.ICE, SpiritualRootAttribute.WATER),
    SENSE_SCAN("神识扫描", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "sense_scan", 12, 120, "神识外放扫过周围，短暂显形附近生灵气息"),
    SENSE_PRESSURE("神识压", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "sense_pressure", 12, 130, "凝神成压迫单个目标，扰乱其行动与攻势"),
    SENSE_NEEDLE("神念针", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "sense_needle", 15, 140, "压缩神念成针刺入目标识海"),
    SENSE_DOMAIN("神识域", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_9, "sense_domain", 22, 190, "短暂展开神识领域压制近身敌人"),
    MIND_READ("读心术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_8, "mind_read", 12, 160, "以神识触碰目标心绪，窥见其虚实并短暂扰神"),
    SENSE_LOCK("神识锁", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_10, "sense_lock", 20, 180, "以神识锁定目标，使其难以隐匿与脱身"),
    DIVINE_SENSE_SCAN("神识探查", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "divine_sense_scan", 18, 180, "筑基神识外放探查大范围气息，可破低阶隐匿"),
    DIVINE_SENSE_LOCK("神识锁敌", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "divine_sense_lock", 26, 220, "结丹神识强锁敌踪，压制并破除隐形"),
    SOUL_ATTACK_WAVE("神魂冲击", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "soul_attack_wave", 26, 200, "神魂冲击成波轰出，震乱直线目标识海"),
    SOUL_CRY_SHOCK("啼魂尖啸", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "soul_cry_shock", 26, 240, "啼魂尖啸震荡周身神魂，对鬼物额外有效"),
    BLOOD_SHADOW_ESCAPE("血影遁", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "blood_shadow_escape", 35, 200, "化作血影短距遁行并留下血煞残痕", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    SKY_SUPPORTING_DEMONIC_SKILL("托天魔功", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "sky_supporting_demonic_skill", 32, 260, "托天魔气撑开护身魔穹，短时强化防护", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    MYSTIC_SOUL_GHOST_FIRE("玄魂鬼火", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "mystic_soul_ghost_fire", 30, 180, "以神识点燃阴森鬼火，灼魂并削弱目标", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    MYSTIC_SOUL_BONE_CONDENSING_ART("玄魂凝骨术", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "mystic_soul_bone_condensing_art", 24, 240, "以魂力凝骨护体，强化肉身与抗性", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    BLOOD_LUO_BARRIER("血罗罩", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "blood_luo_barrier", 34, 240, "血煞成罩护身，震退近敌并偏转飞矢", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    YIN_DEMON_SLASH("阴魔斩", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "yin_demon_slash", 32, 190, "阴魔煞气凝成一线斩击，侵蚀护体灵光", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    FIVE_ELEMENT_FUSION_BURST("五行融爆", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.MIDDLE, "five_element_fusion_burst", 48, 320, "五行灵力在一点融汇爆裂，形成自定义五色阵爆压制群敌", SpiritualRootAttribute.METAL, SpiritualRootAttribute.WOOD, SpiritualRootAttribute.WATER, SpiritualRootAttribute.FIRE, SpiritualRootAttribute.EARTH),
    LIFE_FIRE("本命真火", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "life_fire", 42, 320, "元婴本命真火凝成灼魂火线，作为高阶火系秘术攻击", SpiritualRootAttribute.FIRE),
    LIEYAN_TRUE_FIRE_SECRET("真炎焚天", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "lieyan_true_fire_secret", 54, 360, "烈焰功高阶秘术，真火成域焚烧并削弱范围目标", SpiritualRootAttribute.FIRE),

    // 功法系统
    CHANGCHUN_METHOD("长春功", SkillCategory.CULTIVATION_METHOD, Realm.QI_REFINING, "基础修炼功法，适合新手入门"),
    DAYAN_METHOD("大衍诀", SkillCategory.CULTIVATION_METHOD, Realm.FOUNDATION_ESTABLISHMENT, "高阶功法，提升修炼速度 50%"),
    QINGYUAN_SWORD_METHOD("青元剑诀", SkillCategory.CULTIVATION_METHOD, Realm.CORE_FORMATION, "剑修专属功法，攻击力大幅提升"),
    DEVOURING_METHOD("吞噬功法", SkillCategory.CULTIVATION_METHOD, Realm.NASCENT_SOUL, "魔道功法，可吞噬他人修为"),
    BODY_REFINING_METHOD("炼体功法", SkillCategory.CULTIVATION_METHOD, Realm.QI_REFINING, "体修专属，提升防御和体质"),

    // 五行基础法术
    QI_GUIDING("引气入体", SkillCategory.CULTIVATION_METHOD, Realm.QI_REFINING, RealmStage.LAYER_1, "qi_guiding_art", 0, 0, "引导灵力入体，开启练气修行的基础被动"),
    FIREBALL("火球术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "fireball_art", 10, 40, "基础火系法术，发射火球攻击", SpiritualRootAttribute.FIRE),
    FIRE_BULLET("火弹术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "fire_bullet_art", 8, 40, "长春功附录火系攻击法术", SpiritualRootAttribute.FIRE),
    WATER_ARROW("\u6c34\u7bad\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "water_arrow", 8, 40, "\u51dd\u6c34\u6210\u7bad\u7684\u4e94\u884c\u5165\u95e8\u653b\u51fb\u672f", SpiritualRootAttribute.WATER),
    METAL_NEEDLE("\u91d1\u9488\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "metal_needle", 8, 40, "\u51dd\u91d1\u6210\u9488\u7684\u4e94\u884c\u5165\u95e8\u653b\u51fb\u672f", SpiritualRootAttribute.METAL),
    DARK_FLAME("\u6697\u7130\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "dark_flame", 9, 60, "\u4ee5\u6697\u5c5e\u6027\u7075\u529b\u51dd\u6210\u8680\u9b42\u706b\u5f39\u7684\u653b\u51fb\u672f", SpiritualRootAttribute.DARK, SpiritualRootAttribute.HIDDEN_DARK),
    LIGHT_ORB("\u5149\u7403\u672f", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "light_orb", 8, 55, "\u51dd\u5149\u4e3a\u7403\u3001\u6807\u8bb0\u5e76\u9707\u6444\u76ee\u6807\u7684\u653b\u51fb\u672f"),
    WIND_BLADE("风刃术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "wind_blade", 8, 40, "凝风成刃的五行入门攻击术", SpiritualRootAttribute.WIND),
    VINE_ARROW("木箭术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "vine_arrow", 8, 40, "催木灵成箭的五行入门攻击术", SpiritualRootAttribute.WOOD),
    THUNDER_PALM("雷击掌", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "thunder_palm", 9, 55, "掌心凝雷的近身雷系攻击术", SpiritualRootAttribute.THUNDER),
    FLAME_RING("火环术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "flame_ring", 11, 100, "灵焰外扩的近身范围火术", SpiritualRootAttribute.FIRE),
    FROST_ARMOR("寒冰护体", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "frost_armor", 8, 180, "寒气凝甲的冰系护体术", SpiritualRootAttribute.ICE),
    GOLD_BEAM("金芒术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "gold_beam", 10, 70, "凝金成芒的直线穿刺术", SpiritualRootAttribute.METAL),
    ICE_CONE("冰锥术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "ice_cone_art", 10, 40, "基础水系法术，发射冰锥减速敌人", SpiritualRootAttribute.WATER, SpiritualRootAttribute.ICE),
    ICE_FREEZING("冰冻术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "ice_freezing_art", 10, 40, "长春功附录水冰系攻击法术", SpiritualRootAttribute.WATER, SpiritualRootAttribute.ICE),
    VINE_BIND("藤蔓术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "entangling_art", 8, 80, "基础木系法术，束缚敌人", SpiritualRootAttribute.WOOD),
    VOICE_TRANSMISSION("传音术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_2, "voice_transmission_art", 6, 80, "以灵力将声音送入近处修士耳中"),
    EARTH_SPIKE("地刺术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "earth_spike_art", 12, 60, "长春功附录土系攻击法术", SpiritualRootAttribute.EARTH),
    OBJECT_CONTROL("控物术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "object_control_art", 8, 60, "以灵力牵引近处物品或扰乱敌人持器"),
    QUICKSAND("流沙术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "quicksand_art", 12, 120, "凝土化沙困敌的基础土系术法", SpiritualRootAttribute.EARTH),
    EARTH_WALL("土墙术", SkillCategory.SPELL, Realm.QI_REFINING, "基础土系法术，召唤防御土墙", SpiritualRootAttribute.EARTH),
    METAL_BLADE("金刃术", SkillCategory.SPELL, Realm.QI_REFINING, "基础金系法术，发射锐利金刃", SpiritualRootAttribute.METAL),

    // 高阶法术
    THUNDER_STRIKE("雷击术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "thunder_strike_art", 12, 60, "雷系入门法术，召唤天雷", SpiritualRootAttribute.THUNDER),
    FIVE_ELEMENT_ROTATION("五行轮转", SkillCategory.SPELL, Realm.CORE_FORMATION, "五行大法，连续释放五行法术"),
    SWORD_FORMATION("剑阵", SkillCategory.SPELL, Realm.NASCENT_SOUL, "剑修终极法术，布置飞剑剑阵"),

    // 辅助法术
    LIGHTNESS_SKILL("轻身术", SkillCategory.SPELL, Realm.QI_REFINING, "提升移动速度和跳跃高度"),
    INVISIBILITY("隐身术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, "短时间内隐身"),
    EARTH_ESCAPE("土遁步", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "earth_escape_step", 15, 100, "短距离土遁瞬移"),

    // 神识类法术
    SOUL_SEARCH("搜魂术", SkillCategory.SPELL, Realm.NASCENT_SOUL, "搜索目标记忆（PVE）", SpiritualRootAttribute.DARK),
    DETECTION("灵气探测", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_10, "aura_detection_art", 5, 200, "探测神识范围内的灵气波动"),

    // 生活技能
    ALCHEMY("炼丹术", SkillCategory.CRAFTING, Realm.QI_REFINING, "炼制丹药，等级影响品质"),
    ARTIFACT_REFINING("炼器术", SkillCategory.CRAFTING, Realm.FOUNDATION_ESTABLISHMENT, "炼制法宝和装备"),
    FORMATION("阵法", SkillCategory.CRAFTING, Realm.CORE_FORMATION, "布置灵气阵法"),
    TALISMAN_CRAFTING("符箓绘制", SkillCategory.CRAFTING, Realm.QI_REFINING, "绘制符箓"),

    // 特殊技能
    FLYING_SWORD_BEGINNER("御剑飞行初", SkillCategory.SPECIAL, Realm.QI_REFINING, RealmStage.LAYER_7, "flying_sword_beginner", 0, 20, "练气期基础御剑飞行"),
    SINGLE_SWORD_THRUST("单剑刺击", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_7, "single_sword_thrust", 20, 20, "发射一把飞剑刺击目标"),
    THREE_TALENT_SWORD_ARRAY("三才剑阵", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_13, "three_talent_sword_array", 40, 60, "三把飞剑同时出击"),
    DIVINE_SENSE_EXPANSION("神识扩展", SkillCategory.SPECIAL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "divine_sense_expansion", 0, 0, "筑基后神识范围提升五成"),
    FLYING_SWORD_ADVANCED("御剑飞行进阶", SkillCategory.SPECIAL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "flying_sword_advanced", 0, 20, "筑基期进阶御剑飞行，每秒消耗灵力"),
    AURA_BODY_SHIELD("罡气护体", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "aura_body_shield", 50, 300, "真元化罡，抵消下一次伤害"),
    WATER_SHIELD("水罩术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "water_shield_art", 30, 220, "水灵成罩，抵御火系与冲击", SpiritualRootAttribute.WATER),
    EARTH_PRISON("土牢术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "earth_prison_art", 35, 180, "操土成牢，困住敌人", SpiritualRootAttribute.EARTH),
    WIND_BINDING("风缚之术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "wind_binding_art", 28, 160, "风流成锁，束缚敌人", SpiritualRootAttribute.WIND),
    WIND_WALL("风墙术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "wind_wall_art", 32, 200, "凝聚气流偏转飞矢并减弱冲击", SpiritualRootAttribute.WIND),
    FIVE_ELEMENTS_ESCAPE("五行遁术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.MIDDLE, "five_elements_escape_art", 60, 400, "借五行灵根向前遁行二十格", SpiritualRootAttribute.METAL, SpiritualRootAttribute.WOOD, SpiritualRootAttribute.WATER, SpiritualRootAttribute.FIRE, SpiritualRootAttribute.EARTH),
    BIG_DIPPER_SWORD_ARRAY("北斗剑阵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.LATE, "big_dipper_sword_array", 80, 160, "七把飞剑成阵齐射"),
    FORMATION_SENSE("阵法感知", SkillCategory.SPECIAL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.PEAK, "formation_sense", 10, 200, "以神识感知附近阵法与灵力边界"),
    BEAST_TAMING("驭兽术", SkillCategory.SPECIAL, Realm.FOUNDATION_ESTABLISHMENT, "契约和驯服灵兽"),
    PUPPET_CONTROL("傀儡操控", SkillCategory.SPECIAL, Realm.CORE_FORMATION, "操控战斗傀儡"),
    MULTI_CASTING("分神双放", SkillCategory.SPECIAL, Realm.NASCENT_SOUL, "分神双放：主术释放时可联动额外术位同步施展（共享灵力与冷却）"),

    BUDDHA_LIGHT("佛光", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "buddha_light", 19, 170, "佛光铺开金色莲纹，净化隐匿并克制妖魔鬼物"),
    SARIRA_SHIELD("舍利护体", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "sarira_shield", 12, 190, "舍利光珠护住周身，偏折飞矢并震退妖邪"),
    DEMON_SUBDUE_PALM("降魔掌", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "demon_subdue_palm", 22, 150, "金色掌印近距轰出，击退并镇压前方目标"),
    ZEN_PULSE("禅波", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "zen_pulse", 15, 150, "禅音化作环形脉冲扰乱近敌神识与行动"),
    VAJRA_PALM("金刚掌", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "vajra_palm", 18, 145, "金刚掌力凝成金白光束贯穿前方目标"),
    DAJIN_BUDDHIST_VAJRA("大晋金刚杵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "dajin_buddhist_vajra", 18, 170, "佛门金刚杵虚影落下，重击并强力镇压单个目标"),
    RIGHTEOUS_QI("浩然正气", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "righteous_qi", 12, 160, "浩然正气护身，清除扰神并震慑邪祟"),
    WORD_SUPPRESS("言镇", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "word_suppress", 16, 150, "口含真言凝成字印，镇压单个目标"),
    SCROLL_STRIKE("书卷击", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "scroll_strike", 18, 145, "书卷灵光横击前方，以卷轴轨迹打断目标"),
    INK_SEA("墨海", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "ink_sea", 20, 210, "墨意化海困住一片战场，迟滞并遮蔽敌人"),
    CONFUCIAN_RIGHTEOUS_QI("儒门浩然气", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "confucian_righteous_qi", 18, 170, "浩然气凝成金白长虹，贯穿并镇压前方目标"),
    SMALL_SWORD_ARRAY("小剑阵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "small_sword_array", 20, 160, "坤吴阵纹凝成小型剑阵，以自定义剑痕粒子绞杀落点敌人", SpiritualRootAttribute.METAL),
    ILLUSION_FORMATION("迷踪阵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "illusion_formation", 12, 150, "幻阵扰乱目标感知，显形并迟滞阵内敌人"),
    SPIRIT_GATHER_ARRAY("聚灵阵术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "spirit_gather_array", 12, 220, "短时聚拢周身灵气，回补灵力并稳住气机"),
    THUNDER_TRAP_ARRAY("雷劫阵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.MIDDLE, "thunder_trap_array", 27, 220, "雷纹阵柱锁住落点区域，以自定义雷弧轰击目标", SpiritualRootAttribute.THUNDER),
    SEAL_ARRAY("封灵阵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "seal_array", 15, 170, "封灵阵纹压制行动和施法节奏"),
    KILL_SWORD_FORMATION("杀阵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.LATE, "kill_sword_formation", 30, 240, "杀阵剑痕层层落下，对范围目标造成更强阵法伤害", SpiritualRootAttribute.METAL),
    DEFENSE_FORMATION("守阵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "defense_formation", 12, 220, "守阵护住周身，提供防护并偏折飞矢", SpiritualRootAttribute.EARTH),
    SEA_LOCK_ARRAY("镇海锁阵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.MIDDLE, "sea_lock_array", 24, 220, "星宫水禁锁住一片战场，迟滞敌方遁速", SpiritualRootAttribute.WATER),
    STAR_PALACE_PATROL_BEACON("巡海信标", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "star_palace_patrol_beacon", 18, 220, "星宫巡海信标显形近处敌踪并加持身法"),
    FORMATION_TRAP_BASIC("困敌小阵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "formation_trap_basic", 18, 180, "基础困敌阵纹合拢，压制阵中目标"),
    STAR_PALACE_SEAL("镇海印", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "star_palace_seal", 26, 220, "镇海印以星宫阵力镇压落点区域", SpiritualRootAttribute.WATER),
    KUNWU_SEAL_STRIKE("坤吴印击", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "kunwu_seal_strike", 26, 210, "坤吴印诀牵引阵力轰击一片区域"),
    STAR_PALACE_TIDAL_LOCK("镇海潮封", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "star_palace_tidal_lock", 26, 240, "星宫潮封禁制迟滞范围敌人并削弱攻势", SpiritualRootAttribute.WATER),
    ICE_SHARD("冰棱术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "ice_shard", 8, 40, "凝冰成棱的入门投射术", SpiritualRootAttribute.ICE, SpiritualRootAttribute.WATER),
    WOOD_BIND("木缚术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "wood_bind", 8, 80, "木灵藤蔓束缚单体目标", SpiritualRootAttribute.WOOD),
    STEAM_CLOUD("蒸汽云", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "steam_cloud", 8, 100, "水火交蒸成云迟滞范围敌人", SpiritualRootAttribute.WATER, SpiritualRootAttribute.FIRE),
    EVIL_WARD_THUNDER("镇邪雷", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "evil_ward_thunder", 26, 160, "结丹镇邪雷芒投射击溃阴邪", SpiritualRootAttribute.THUNDER),
    METAL_SWORD_FINGER("金剑指", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "metal_sword_finger", 12, 80, "凝金成指芒贯穿前方", SpiritualRootAttribute.METAL),
    GREEN_BAMBOO_SWORD_RAY("青竹剑芒", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "green_bamboo_sword_ray", 26, 150, "青竹剑气凝芒穿刺", SpiritualRootAttribute.WOOD, SpiritualRootAttribute.METAL),
    STAR_SWORD_ARRAY("星辰剑阵", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "star_sword_array", 35, 220, "星芒剑阵覆盖一片战场", SpiritualRootAttribute.METAL),
    SWORD_FORMATION_BASIC("小剑阵式", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "sword_formation_basic", 26, 180, "基础剑阵凝锋斩敌", SpiritualRootAttribute.METAL),
    QINGLUO_POISON_NEEDLE("青罗毒针", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "qingluo_poison_needle", 18, 100, "魔道毒针投射侵蚀目标", SpiritualRootAttribute.DARK),
    DEMON_FLAME("魔炎阵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "demon_flame", 21, 160, "魔炎席卷范围灼魂", SpiritualRootAttribute.FIRE, SpiritualRootAttribute.DARK),
    BLOOD_SACRIFICE("血祭", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "blood_sacrifice", 12, 200, "以血煞自励短时强化攻势", SpiritualRootAttribute.DARK),
    BLOOD_CURSE_MARK("血咒印", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "blood_curse_mark", 28, 160, "血咒烙印削弱目标", SpiritualRootAttribute.DARK),
    DEMON_ARMOR("魔铠", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "demon_armor", 12, 200, "魔气凝铠护体", SpiritualRootAttribute.DARK),
    FOX_PHANTOM_SHIFT("狐影挪移", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "fox_phantom_shift", 18, 160, "幻影身法短距扰动并加速", SpiritualRootAttribute.DARK),
    NETHER_GHOST_WALK("冥鬼游步", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "nether_ghost_walk", 12, 120, "鬼影游步提升身法"),
    YIN_SOUL_DEVOUR("阴魂噬取", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "yin_soul_devour", 14, 140, "阴魂汲取削弱目标并回补自身", SpiritualRootAttribute.DARK),
    SPIRIT_ART_WIND_BLADE("风刃灵术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "spirit_art_wind_blade", 8, 40, "慕兰风刃投射", SpiritualRootAttribute.WIND),
    SPIRIT_ART_THUNDER("雷光灵术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "spirit_art_thunder", 11, 60, "慕兰雷光投射", SpiritualRootAttribute.THUNDER),
    SPIRIT_ART_HEAL("治愈灵术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "spirit_art_heal", 15, 120, "慕兰治愈灵光回补伤势", SpiritualRootAttribute.WOOD),
    SPIRIT_ART_SAND_STORM("沙暴灵术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "spirit_art_sand_storm", 18, 140, "慕兰沙暴范围压制", SpiritualRootAttribute.EARTH, SpiritualRootAttribute.WIND),
    SPIRIT_ART_EARTH_WALL("土墙灵术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "spirit_art_earth_wall", 12, 160, "慕兰土墙护身", SpiritualRootAttribute.EARTH),
    SPIRIT_ART_HOLY_LIGHT("圣光灵术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "spirit_art_holy_light", 17, 140, "圣光治愈并净化", SpiritualRootAttribute.FIRE),
    SPIRIT_ART_WIND_RIDE("御风灵术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "spirit_art_wind_ride", 10, 140, "御风加速身法", SpiritualRootAttribute.WIND),
    VAJRA_BODY("金刚体", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "vajra_body", 12, 200, "炼体金刚护身", SpiritualRootAttribute.EARTH),
    IRON_SKIN("铁皮功", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "iron_skin", 12, 180, "炼体铁皮强化防御", SpiritualRootAttribute.METAL),
    DRAGON_STRENGTH("龙力功", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "dragon_strength", 12, 180, "炼体龙力增强攻势", SpiritualRootAttribute.EARTH),
    BODY_FLASH("闪身", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "body_flash", 10, 80, "炼体闪身短距加速突进"),
    PALM_WIND("掌风", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "palm_wind", 12, 60, "近身掌风冲击", SpiritualRootAttribute.WIND),
    BONE_CRUSH("碎骨拳", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "bone_crush", 16, 80, "近身碎骨重拳", SpiritualRootAttribute.EARTH),
    TIANYUAN_JOINT_ARRAY("天渊合阵", SkillCategory.SPELL, Realm.SOUL_TRANSFORMATION, RealmStage.EARLY, "tianyuan_joint_array", 40, 260, "天渊合阵范围压制（高阶阵法术）"),
    SOUL_DEVOUR("摄魂术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "soul_devour", 17, 140, "魔道摄魂削弱目标神识与行动", SpiritualRootAttribute.DARK),
    DEMON_FORM("魔化", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "demon_form", 12, 220, "短时魔化强化攻防（非真实变身实体）", SpiritualRootAttribute.DARK),
    DEMON_CONTRACT("魔契", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "demon_contract", 19, 160, "魔契烙印压制单体目标", SpiritualRootAttribute.DARK),
    HEHUAN_CHARM("媚惑术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "hehuan_charm", 18, 140, "合欢媚术扰乱目标心神", SpiritualRootAttribute.DARK),
    BLOOD_CURSE_STRIKE("血咒击", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "blood_curse_strike", 18, 120, "血咒凝击贯穿前方", SpiritualRootAttribute.DARK),
    POISON_MIST("毒雾术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "poison_mist", 18, 150, "毒雾笼罩迟滞并侵蚀范围敌人", SpiritualRootAttribute.WOOD, SpiritualRootAttribute.DARK),
    DEMON_CLAW("魔爪", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "demon_claw", 18, 100, "魔爪近距撕扯目标", SpiritualRootAttribute.DARK),
    BLOOD_DEMON_SLASH("血魔斩", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "blood_demon_slash", 28, 140, "血刃近身重斩", SpiritualRootAttribute.DARK, SpiritualRootAttribute.METAL),
    SOUL_BANNER_WAVE("招魂幡浪", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "soul_banner_wave", 22, 180, "招魂幡浪冲击一片阴魂", SpiritualRootAttribute.DARK),
    YIN_LUO_GHOST_CLOAK("阴罗鬼cloak", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "yin_luo_ghost_cloak", 18, 200, "阴罗鬼cloak隐匿身形", SpiritualRootAttribute.DARK),
    GHOST_WALK("鬼步", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "ghost_walk", 18, 120, "鬼步身法加速并扰动敌踪", SpiritualRootAttribute.DARK),
    SHORT_TELEPORT("瞬步", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "short_teleport", 12, 100, "短距瞬步位移"),
    WIND_RIDE("御风", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "wind_ride", 12, 120, "御风提升身法", SpiritualRootAttribute.WIND),
    SHADOW_FLASH("影闪", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "shadow_flash", 12, 100, "影闪短距遁形", SpiritualRootAttribute.DARK),
    WATER_ESCAPE("水遁术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "water_escape", 18, 140, "水遁加速脱身", SpiritualRootAttribute.WATER),
    FIRE_ESCAPE("火遁术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "fire_escape", 18, 140, "火遁加速突进", SpiritualRootAttribute.FIRE),
    QI_BURST_PALM("气爆掌", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "qi_burst_palm", 14, 70, "气爆掌近身冲击"),
    BODY_HARDNESS("金刚不坏", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "body_hardness", 26, 240, "炼体金刚不坏护身", SpiritualRootAttribute.EARTH, SpiritualRootAttribute.METAL),
    TIANMO_BLOOD_ARMOR("天魔血甲", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "tianmo_blood_armor", 18, 200, "天魔血甲强化物防", SpiritualRootAttribute.DARK),
    SMUGGLE_RIFT_STEP("暗港遁步", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "smuggle_rift_step", 16, 120, "逆星暗港短距遁步"),
    INVERSE_STAR_SHADOW_STEP("逆星影步", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "inverse_star_shadow_step", 18, 140, "逆星影步遁走并降低被锁定感"),
    XUEWU_BLOOD_CURSE_MARK("血巫咒印", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "xuewu_blood_curse_mark", 18, 150, "血巫咒印标记并削弱目标", SpiritualRootAttribute.DARK),
    FIRE_TALISMAN("烈火符", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "fire_talisman", 10, 40, "烈火符凝焰投射", SpiritualRootAttribute.FIRE),
    ICE_TALISMAN("寒冰符", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "ice_talisman", 9, 40, "寒冰符凝冰投射", SpiritualRootAttribute.ICE, SpiritualRootAttribute.WATER),
    TELEPORT_TALISMAN("遁天符", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "teleport_talisman", 12, 120, "遁天符短距位移"),
    SPIRIT_SHIELD_TALISMAN("护体符", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "spirit_shield_talisman", 12, 160, "护体符强化防护"),
    EXPLOSION_TALISMAN("爆炎符", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "explosion_talisman", 17, 140, "爆炎符范围灼击", SpiritualRootAttribute.FIRE),
    WIND_TALISMAN("神行符", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "wind_talisman", 12, 120, "神行符提升身法", SpiritualRootAttribute.WIND),
    SEAL_TALISMAN("定身符", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "seal_talisman", 12, 100, "定身符束缚单体"),
    GHOST_TALISMAN("驱鬼符", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "ghost_talisman", 14, 120, "驱鬼符冲击阴邪", SpiritualRootAttribute.DARK),
    SPIRIT_CHAIN_TALISMAN_CAST("缚灵符术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "spirit_chain_talisman_cast", 16, 140, "缚灵符束缚目标"),
    GOLDEN_ARMOR_TALISMAN_CAST("金刚符术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "golden_armor_talisman_cast", 14, 180, "金刚符强化护体", SpiritualRootAttribute.METAL),
    THUNDER_TALISMAN_STORM("雷符暴雨", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "thunder_talisman_storm", 32, 200, "雷符暴雨轰击范围", SpiritualRootAttribute.THUNDER),
    PALM_THUNDER("掌心雷", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "palm_thunder", 10, 55, "掌心雷近距投射", SpiritualRootAttribute.THUNDER),
    BLOOD_ESCAPE("血遁", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "blood_escape", 10, 100, "血遁短距加速", SpiritualRootAttribute.DARK),
    EARTH_BURROW("土遁", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "earth_burrow", 10, 100, "土遁短距遁行", SpiritualRootAttribute.EARTH),
    GREEN_SHIELD("青元护体", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "green_shield", 10, 160, "青元护体强化防护", SpiritualRootAttribute.WOOD),
    SOUL_CHOP("斩魂诀", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "soul_chop", 10, 80, "斩魂诀投射侵蚀", SpiritualRootAttribute.DARK),
    DEMON_ROAR("魔啸", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "demon_roar", 10, 120, "魔啸冲击范围", SpiritualRootAttribute.DARK),
    SPIRIT_NEEDLE("灭灵针", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "spirit_needle", 10, 50, "灭灵针锐芒投射", SpiritualRootAttribute.METAL),
    ICE_PRISON("玄冰牢", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "ice_prison", 10, 140, "玄冰牢束缚目标", SpiritualRootAttribute.ICE),
    FIRE_RAIN("火雨术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "fire_rain", 10, 140, "火雨术范围灼击", SpiritualRootAttribute.FIRE),
    SAND_BURY("流沙术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "sand_bury", 10, 120, "流沙术困滞范围", SpiritualRootAttribute.EARTH),
    GHOST_BIND("缚鬼索", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "ghost_bind", 10, 100, "缚鬼索束缚目标", SpiritualRootAttribute.DARK),
    CORPSE_EXPLODE("尸爆", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_7, "corpse_explode", 10, 160, "尸爆冲击范围", SpiritualRootAttribute.DARK),
    SWORD_RAIN("剑雨术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_7, "sword_rain", 10, 160, "剑雨术范围斩击", SpiritualRootAttribute.METAL),
    MIRROR_REFLECT("镜光反", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "mirror_reflect", 10, 180, "镜光反护身偏折"),
    WATER_DRAGON("水龙术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "water_dragon", 10, 90, "水龙术投射冲击", SpiritualRootAttribute.WATER),
    GOLD_NEEDLE("金针术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_3, "gold_needle", 10, 40, "金针术锐芒投射", SpiritualRootAttribute.METAL),
    YIN_FIRE("阴火焚", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "yin_fire", 10, 140, "阴火焚范围灼魂", SpiritualRootAttribute.DARK, SpiritualRootAttribute.FIRE),
    YANG_BURST("阳爆", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "yang_burst", 10, 140, "阳爆范围冲击", SpiritualRootAttribute.FIRE),
    FIVE_ELEMENTS_PALM("五行掌", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "five_elements_palm", 10, 70, "五行掌近身冲击"),
    SOUL_SEARCH_SPELL("搜魂术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_8, "soul_search_spell", 12, 160, "搜魂术窥探并扰神", SpiritualRootAttribute.DARK),
    SPIRIT_SEAL("封灵印", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "spirit_seal", 12, 140, "封灵印压制目标"),
    DEMON_SUBDUE_SEAL("伏魔印", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "demon_subdue_seal", 12, 140, "伏魔印镇压邪祟"),
    NASCENT_SOUL_ESCAPE("元婴遁", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "nascent_soul_escape", 12, 160, "元婴遁短距脱身"),
    DOMAIN_COMPRESS("领域压缩", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "domain_compress", 45, 240, "领域压缩压制范围敌人"),
    VOID_REFINE_TOUCH("炼虚触", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "void_refine_touch", 37, 180, "炼虚触削弱单体"),
    SPIRIT_SENSE_MERGE("神魂融合", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "spirit_sense_merge", 12, 220, "神魂融合强化自身"),
    SPACE_TEAR_SLASH("裂空斩", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "space_tear_slash", 47, 160, "裂空斩贯穿前方", SpiritualRootAttribute.METAL),
    TRIBULATION_REDIRECT("引劫术", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "tribulation_redirect", 12, 260, "引劫术扰乱目标气机", SpiritualRootAttribute.THUNDER),
    BLOODLINE_AWAKEN("血脉觉醒", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "bloodline_awaken", 12, 240, "血脉觉醒短时强化"),
    MULAN_WIND_BLADE("慕兰风刃", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "mulan_wind_blade", 18, 100, "慕兰风刃投射", SpiritualRootAttribute.WIND),
    MULAN_EARTH_WALL("慕兰土墙", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "mulan_earth_wall", 18, 160, "慕兰土墙护身", SpiritualRootAttribute.EARTH),
    SPIRIT_ART_HOLY_FEATHER_GUARD("圣羽护体", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "spirit_art_holy_feather_guard", 35, 200, "圣羽护体强化防护"),
    PUPPET_SELF_DESTRUCT("傀爆", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "puppet_self_destruct", 30, 200, "傀爆范围冲击（无实体诚实MVP）"),
    SPIRIT_THREAD_CONTROL("控灵丝", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "spirit_thread_control", 10, 140, "控灵丝强化操控"),
    ARRAY_PUPPET("阵傀", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "array_puppet", 19, 180, "阵傀困敌（无实体诚实MVP）"),
    PUPPET_ARRAY_TRAP("机关阵术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "puppet_array_trap", 20, 180, "机关阵术困滞范围"),
    PUPPET_SUMMON_BASIC("唤傀术", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "puppet_summon_basic", 26, 220, "唤傀术自强化标记（无实体诚实MVP）"),
    CORPSE_EXPLOSION("尸爆术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "corpse_explosion", 20, 160, "尸爆术范围冲击", SpiritualRootAttribute.DARK),
    SOUL_BANNER("招魂", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "soul_banner", 11, 140, "招魂削弱目标", SpiritualRootAttribute.DARK),
    SOUL_ANCHOR_RITE("魂锚仪式", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "soul_anchor_rite", 25, 220, "魂锚仪式稳固自身", SpiritualRootAttribute.DARK),
    YIN_SOUL_BURST("阴婴爆散", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "yin_soul_burst", 55, 260, "阴婴爆散范围冲击", SpiritualRootAttribute.DARK),
    POLUO_SOUL_PULL("夺魂牵引", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "poluo_soul_pull", 18, 150, "夺魂牵引迟滞目标", SpiritualRootAttribute.DARK),
    HEAVEN_DEMON_HAND("天魔手", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "heaven_demon_hand", 35, 120, "天魔手近身重击", SpiritualRootAttribute.DARK),
    DEMON_QI_BURST("魔气爆", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "demon_qi_burst", 32, 180, "魔气爆范围冲击", SpiritualRootAttribute.DARK),
    SOUL_CONTRACT("魂契", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "soul_contract", 20, 160, "魂契压制单体", SpiritualRootAttribute.DARK),
    DEMON_SOUL_DEVOUR("魔噬魂", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "demon_soul_devour", 27, 160, "魔噬魂削弱目标", SpiritualRootAttribute.DARK),
    BARBARIAN_ROAR("蛮荒咆哮", SkillCategory.SPELL, Realm.VOID_REFINEMENT, RealmStage.EARLY, "barbarian_roar", 50, 200, "蛮荒咆哮冲击压制", SpiritualRootAttribute.EARTH),
    HEHUAN_SOUL_CHARM("合欢迷心", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "hehuan_soul_charm", 18, 140, "合欢迷心扰乱心神", SpiritualRootAttribute.DARK),
    SPIRIT_ART_LIGHTNING_PALM("雷掌灵术", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "spirit_art_lightning_palm", 26, 100, "雷掌灵术近距轰击", SpiritualRootAttribute.THUNDER),
    SPIRIT_FENGYUAN_WIND_WALL("风元风墙", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "spirit_fengyuan_wind_wall", 18, 160, "风元风墙护身偏折", SpiritualRootAttribute.WIND),
    SPIRIT_ART_ARRAY_ANCHOR("阵眼定灵", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "spirit_art_array_anchor", 20, 180, "阵眼定灵稳固自身"),
    YIN_BODY_CONDENSE("凝阴体", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "yin_body_condense", 26, 200, "凝阴体护身强化", SpiritualRootAttribute.DARK),
    SPIRIT_WALL("灵墙术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "spirit_wall", 12, 160, "灵墙术护身偏折"),
    BLOOD_SWORD("血剑术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "blood_sword", 12, 80, "血剑术投射斩击", SpiritualRootAttribute.DARK, SpiritualRootAttribute.METAL),
    PHANTOM_CLONE("幻影分身", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "phantom_clone", 12, 180, "幻影分身扰敌"),
    SKY_HOOK("摄魂钩", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "sky_hook", 12, 90, "摄魂钩投射牵引", SpiritualRootAttribute.DARK),
    GROUND_SPIKE("地刺阵", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "ground_spike", 12, 120, "地刺阵困滞范围", SpiritualRootAttribute.EARTH),
    LIGHTNING_CHAIN("连锁雷", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "lightning_chain", 14, 140, "连锁雷跳跃轰击", SpiritualRootAttribute.THUNDER),
    FROST_BREATH("寒息", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "frost_breath", 12, 100, "寒息锥形迟滞", SpiritualRootAttribute.ICE),
    MOLTEN_SPLASH("熔岩溅", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_6, "molten_splash", 12, 130, "熔岩溅范围灼击", SpiritualRootAttribute.FIRE),
    SPIRIT_ABSORB("摄灵术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_7, "spirit_absorb", 14, 140, "摄灵术削弱并汲取", SpiritualRootAttribute.DARK),
    BONE_ARMOR("骨甲术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "bone_armor", 12, 180, "骨甲术护体", SpiritualRootAttribute.DARK),
    STAR_FALL("坠星术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_8, "star_fall", 16, 160, "坠星术范围轰击"),
    VOID_SLASH("虚空斩", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_7, "void_slash", 14, 90, "虚空斩近身重击", SpiritualRootAttribute.METAL),
    HEAVEN_PUNISH("天罚术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_9, "heaven_punish", 18, 180, "天罚术范围雷击", SpiritualRootAttribute.THUNDER),
    BEAST_TAME_CALL("驭兽啸", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "beast_tame_call", 16, 140, "驭兽啸威慑目标"),
    SPIRIT_BEAST_CONTRACT("灵兽契约术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "spirit_beast_contract", 18, 180, "灵兽契约术标记强化（无实体诚实MVP）"),
    VOID_RIFT_SLASH("裂隙斩", SkillCategory.SPELL, Realm.VOID_REFINEMENT, RealmStage.EARLY, "void_rift_slash", 40, 160, "裂隙斩贯穿前方", SpiritualRootAttribute.METAL),
    GREAT_VEHICLE_PALM("大乘神掌", SkillCategory.SPELL, Realm.MAHAYANA, RealmStage.EARLY, "great_vehicle_palm", 60, 200, "大乘神掌近距轰击"),
    DEFENSIVE_PEARL_LIGHT("护体珠光", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "defensive_pearl_light", 28, 200, "护体珠光强化防护"),
    MAGNET_CONTROL("元磁控物", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "magnet_control", 26, 160, "元磁控物牵制目标", SpiritualRootAttribute.METAL),
    NASCENT_SOUL_AVATAR("元婴出窍", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "nascent_soul_avatar", 30, 240, "元婴出窍强化神识与身法"),
    DEITY_TRANSFORMATION_DOMAIN("化神领域", SkillCategory.SPELL, Realm.SOUL_TRANSFORMATION, RealmStage.EARLY, "deity_transformation_domain", 48, 260, "化神领域范围压制"),
    LINGZU_PEARL_BARRAGE("灵珠连射", SkillCategory.SPELL, Realm.UNITY, RealmStage.EARLY, "lingzu_pearl_barrage", 40, 140, "灵珠连射投射"),
    STAR_PALACE_SEAL_BURST("星宫封灵爆", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "star_palace_seal_burst", 20, 160, "星宫封灵爆压制目标", SpiritualRootAttribute.WATER),
    RIVER_ESCAPE("水遁", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_4, "river_escape", 12, 120, "水遁加速脱身", SpiritualRootAttribute.WATER),
    WIND_ESCAPE_MOVE("风遁术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "wind_escape", 18, 140, "风遁术加速身法", SpiritualRootAttribute.WIND),
    DAYAN_EYE("大衍神眼", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "dayan_eye", 14, 160, "大衍神眼探查显形"),
    TIANFU_GOLDEN_CHAIN("天符金链", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "tianfu_golden_chain", 18, 150, "天符金链束缚目标", SpiritualRootAttribute.METAL),
    BLOOD_CORRUPTION("污血术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "blood_corruption", 16, 140, "污血术持续侵蚀", SpiritualRootAttribute.DARK),
    YIN_CORROSION("阴蚀", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "yin_corrosion", 16, 140, "阴蚀持续削弱", SpiritualRootAttribute.DARK),
SPIRIT_ART_BEAST_CALL("唤兽灵术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "spirit_art_beast_call", 12, 220, "文本材料summon：唤兽灵术"),
    SPIRIT_ART_HOLY_BEAST_CALL("圣兽唤灵术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "spirit_art_holy_beast_call", 25, 220, "文本材料summon：圣兽唤灵术"),
    GHOST_KING_AVATAR("鬼王化身", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "ghost_king_avatar", 40, 220, "文本材料summon：鬼王化身"),
    GUILING_CORPSE_SUMMON("唤尸术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "guiling_corpse_summon", 18, 220, "文本材料summon：唤尸术"),
    BEAST_SUMMON("唤兽术", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "beast_summon", 10, 220, "文本材料summon：唤兽术"),
    GOLD_DEVOUR_SWARM("噬金虫群", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "gold_devour_swarm", 26, 220, "文本材料summon：噬金虫群"),
    TREASURE_APPRAISAL_GLIMPSE("鉴宝灵光", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "treasure_appraisal_glimpse", 8, 140, "文本材料inspect：鉴宝灵光"),
    SUMMON_WOOD_PUPPET("唤木傀", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "summon_wood_puppet", 12, 220, "文本材料summon：唤木傀"),
    PUPPET_SWARM("傀群术", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "puppet_swarm", 12, 220, "文本材料summon：傀群术"),
    IRON_PUPPET("铁傀召", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "iron_puppet", 12, 220, "文本材料summon：铁傀召"),
    PUPPET_CONTROL_BASIC("控傀诀", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "puppet_control_basic", 8, 140, "文本材料command：控傀诀"),
    PUPPET_SWARM_COMMAND("群傀号令", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "puppet_swarm_command", 30, 220, "文本材料summon：群傀号令"),
    BEAST_SOUL_PUPPET_BIND("兽魂傀绑", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "beast_soul_puppet_bind", 22, 140, "文本材料craft_gate：兽魂傀绑"),
    SECOND_NASCENT_SOUL("第二元婴", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "second_nascent_soul", 12, 220, "文本材料summon：第二元婴"),
    SWORD_FORMATION_SECRET("万剑归宗（仿）", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "sword_formation_secret", 57, 260, "文本材料ultimate：万剑归宗（仿）"),
    NETHER_CORE_FORM("冥核凝形", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "nether_core_form", 57, 260, "文本材料ultimate：冥核凝形"),
    NINE_PALACE_SEAL_SECRET("九宫封天", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "nine_palace_seal_secret", 74, 260, "文本材料ultimate：九宫封天"),
    DAYAN_PUPPET_LEGION("大衍傀群", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "dayan_puppet_legion", 74, 260, "文本材料ultimate：大衍傀群"),
    STAR_PALACE_HEAVEN_SEAL("星宫天印", SkillCategory.SPELL, Realm.SOUL_TRANSFORMATION, RealmStage.EARLY, "star_palace_heaven_seal", 92, 260, "文本材料ultimate：星宫天印"),
    INVERSE_STAR_REBELLION("逆星乱世", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "inverse_star_rebellion", 57, 260, "文本材料ultimate：逆星乱世"),
    VOID_REFINING_DOMAIN("炼虚领域", SkillCategory.SPELL, Realm.VOID_REFINEMENT, RealmStage.EARLY, "void_refining_domain", 110, 260, "文本材料ultimate：炼虚领域"),
    GREAT_VEHICLE_DHARMA_BODY("法相天地", SkillCategory.SPELL, Realm.MAHAYANA, RealmStage.EARLY, "great_vehicle_dharma_body", 127, 260, "文本材料ultimate：法相天地"),
    SPIRIT_SEVERING_FLASH("炼神一闪", SkillCategory.SPELL, Realm.UNITY, RealmStage.EARLY, "spirit_severing_flash", 145, 260, "文本材料ultimate：炼神一闪"),
    FALLEN_DEMON_TRANSFORM("坠魔变身", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "fallen_demon_transform", 74, 260, "文本材料ultimate：坠魔变身"),
    BLOOD_DEMON_AVATAR("血魔分身", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "blood_demon_avatar", 57, 260, "文本材料ultimate：血魔分身"),
    HEHUAN_UNION_SECRET("双修合欢", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "hehuan_union_secret", 57, 260, "文本材料ultimate：双修合欢"),
    TIANMO_BERSERK("天魔狂化", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "tianmo_berserk", 57, 260, "文本材料ultimate：天魔狂化"),
    ILLUSION_WORLD("幻界", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "illusion_world", 74, 260, "文本材料ultimate：幻界"),
    BEAST_SOUL_FUSION("兽魂融合", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "beast_soul_fusion", 57, 260, "文本材料ultimate：兽魂融合"),
    SPATIAL_TEAR_ESCAPE("破空遁", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "spatial_tear_escape", 74, 260, "文本材料ultimate：破空遁"),
    WAN_SWORD_RETURN("万剑归宗（仿）", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "wan_sword_return", 74, 260, "文本材料ultimate：万剑归宗（仿）"),
    VOID_PALACE_HEAVEN_EARTH("天地阴阳大挪移（仿）", SkillCategory.SPELL, Realm.SOUL_TRANSFORMATION, RealmStage.EARLY, "void_palace_heaven_earth", 92, 260, "文本材料ultimate：天地阴阳大挪移（仿）"),
    TRUE_IMMORTAL_SWORD_ART("真灵剑诀（仿）", SkillCategory.SPELL, Realm.UNITY, RealmStage.EARLY, "true_immortal_sword_art", 145, 260, "文本材料ultimate：真灵剑诀（仿）"),
    TIANMO_DEMON_BODY_SECRET("天魔真身", SkillCategory.SPELL, Realm.SOUL_TRANSFORMATION, RealmStage.EARLY, "tianmo_demon_body_secret", 18, 260, "文本材料secret_art：天魔真身"),
    HEHUAN_SOUL_DEVOUR_SECRET("合欢噬魂", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "hehuan_soul_devour_secret", 18, 260, "文本材料secret_art：合欢噬魂"),
    INVERSE_STAR_VOID_ESCAPE("逆星虚空遁", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "inverse_star_void_escape", 18, 260, "文本材料secret_art：逆星虚空遁"),
    PILL_SOUL_CONDENSE_SECRET("丹魂凝华", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "pill_soul_condense_secret", 18, 260, "文本材料secret_art：丹魂凝华"),
    HUADAO_SLASH_SECRET("化刀一刀", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "huadao_slash_secret", 18, 260, "文本材料secret_art：化刀一刀"),
    MULAN_HOLY_BIRD_CALL("圣禽唤灵", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "mulan_holy_bird_call", 18, 260, "文本材料secret_art：圣禽唤灵"),
    BEAST_SOUL_FUSION_SECRET("兽魂合体", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "beast_soul_fusion_secret", 18, 260, "文本材料secret_art：兽魂合体"),
    QINGLUO_TEN_POISON_SEAL("十毒封脉", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "qingluo_ten_poison_seal", 18, 260, "文本材料secret_art：十毒封脉"),
    WANHU_THOUSAND_PHANTOM_DOMAIN("千幻域", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "wanhu_thousand_phantom_domain", 18, 260, "文本材料secret_art：千幻域"),
    TIANYUAN_BOUNDARY_BREAK("界壁裂隙", SkillCategory.SPELL, Realm.SOUL_TRANSFORMATION, RealmStage.EARLY, "tianyuan_boundary_break", 18, 260, "文本材料secret_art：界壁裂隙"),
    YINLUO_SOUL_HARVEST("阴罗摄魂", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "yinluo_soul_harvest", 18, 260, "文本材料secret_art：阴罗摄魂"),
    INVERSE_STAR_COVERT_ULTIMATE_SECRET("逆星匿踪", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "inverse_star_covert_ultimate_secret", 18, 260, "文本材料secret_art：逆星匿踪"),
    DEMONIC_GUILING_ULTIMATE_SECRET("鬼灵尸潮", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "demonic_guiling_ultimate_secret", 18, 260, "文本材料secret_art：鬼灵尸潮"),
    YIN_CLUSTER_GHOST_ULTIMATE_SECRET("阴魂聚煞", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "yin_cluster_ghost_ultimate_secret", 18, 260, "文本材料secret_art：阴魂聚煞"),
    PUPPET_QIANZHU_ULTIMATE_SECRET("千竹傀阵", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "puppet_qianzhu_ultimate_secret", 18, 260, "文本材料secret_art：千竹傀阵"),
    PUPPET_YULING_ULTIMATE_SECRET("御灵万傀", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "puppet_yuling_ultimate_secret", 18, 260, "文本材料secret_art：御灵万傀"),
    BLADE_GIANT_SWORD_ULTIMATE_SECRET("巨剑开山", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "blade_giant_sword_ultimate_secret", 18, 260, "文本材料secret_art：巨剑开山"),
    ARTIFACT_SPIRIT_AWAKEN_SECRET("器灵初醒", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "artifact_spirit_awaken_secret", 35, 260, "文本材料secret_art：器灵初醒"),
    AUCTION_BID_INSIGHT_SECRET("竞价天机", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "auction_bid_insight_secret", 20, 260, "文本材料secret_art：竞价天机"),
    CAST_FIRE_BURST_TALISMAN("爆炎符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_fire_burst_talisman", 8, 140, "文本材料talisman_consume：爆炎符·瞬发"),
    CAST_ICE_SEAL_TALISMAN("冰封符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_ice_seal_talisman", 8, 140, "文本材料talisman_consume：冰封符·瞬发"),
    CAST_ESCAPE_HEAVEN_TALISMAN("遁天符·瞬发", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "cast_escape_heaven_talisman", 8, 140, "文本材料talisman_consume：遁天符·瞬发"),
    CAST_SPIRIT_FIX_TALISMAN("定神符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_spirit_fix_talisman", 8, 140, "文本材料talisman_consume：定神符·瞬发"),
    CAST_THUNDER_TALISMAN("雷霄符·瞬发", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "cast_thunder_talisman", 8, 140, "文本材料talisman_consume：雷霄符·瞬发"),
    CAST_SOUL_LOCK_TALISMAN("锁魂符·瞬发", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "cast_soul_lock_talisman", 8, 140, "文本材料talisman_consume：锁魂符·瞬发"),
    CAST_TELEPORT_ARRAY_TALISMAN("传送符·瞬发", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "cast_teleport_array_talisman", 8, 140, "文本材料talisman_consume：传送符·瞬发"),
    CAST_BEAST_CONTRACT_TALISMAN("御兽契符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_beast_contract_talisman", 8, 140, "文本材料talisman_consume：御兽契符·瞬发"),
    CAST_ANTI_DEMON_TALISMAN("驱魔符·瞬发", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "cast_anti_demon_talisman", 8, 140, "文本材料talisman_consume：驱魔符·瞬发"),
    CAST_YIN_PROTECT_TALISMAN("阴灵护符·瞬发", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "cast_yin_protect_talisman", 8, 140, "文本材料talisman_consume：阴灵护符·瞬发"),
    CAST_GHOST_HIDE_TALISMAN("敛魂符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_ghost_hide_talisman", 8, 140, "文本材料talisman_consume：敛魂符·瞬发"),
    CAST_SPACE_ANCHOR_TALISMAN("定空符·瞬发", SkillCategory.SPELL, Realm.CORE_FORMATION, RealmStage.EARLY, "cast_space_anchor_talisman", 8, 140, "文本材料talisman_consume：定空符·瞬发"),
    CAST_LIFE_SAVE_TALISMAN("替身符·瞬发", SkillCategory.SPELL, Realm.NASCENT_SOUL, RealmStage.EARLY, "cast_life_save_talisman", 8, 140, "文本材料talisman_consume：替身符·瞬发"),
    CAST_EARTH_WALL_TALISMAN("土墙符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_earth_wall_talisman", 8, 140, "文本材料talisman_consume：土墙符·瞬发"),
    CAST_MIRAGE_HEART_TALISMAN("幻心符·瞬发", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "cast_mirage_heart_talisman", 8, 140, "文本材料talisman_consume：幻心符·瞬发"),
    CAST_INVISIBILITY_TALISMAN("匿形符·瞬发", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "cast_invisibility_talisman", 8, 140, "文本材料talisman_consume：匿形符·瞬发"),
    CAST_SPIRIT_GATHER_TALISMAN("聚灵符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_spirit_gather_talisman", 8, 140, "文本材料talisman_consume：聚灵符·瞬发"),
    CAST_ILLUSION_TALISMAN("迷踪符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_illusion_talisman", 8, 140, "文本材料talisman_consume：迷踪符·瞬发"),
    CAST_STAR_PALACE_PATROL_TALISMAN("星宫巡海符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_star_palace_patrol_talisman", 8, 140, "文本材料talisman_consume：星宫巡海符·瞬发"),
    CAST_GOLDEN_ARMOR_TALISMAN("金刚符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_golden_armor_talisman", 8, 140, "文本材料talisman_consume：金刚符·瞬发"),
    CAST_INVERSE_STAR_CIPHER_TALISMAN("逆星暗号符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_inverse_star_cipher_talisman", 8, 140, "文本材料talisman_consume：逆星暗号符·瞬发"),
    CAST_BU_TIAN_TALISMAN("补天符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_bu_tian_talisman", 8, 140, "文本材料talisman_consume：补天符·瞬发"),
    CAST_WOOD_BIND_TALISMAN("木缚符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_wood_bind_talisman", 8, 140, "文本材料talisman_consume：木缚符·瞬发"),
    CAST_METAL_BLADE_TALISMAN("金刃符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_metal_blade_talisman", 8, 140, "文本材料talisman_consume：金刃符·瞬发"),
    CAST_VOID_PALACE_KEY_TALISMAN("虚天引路符·瞬发", SkillCategory.SPELL, Realm.QI_REFINING, RealmStage.LAYER_5, "cast_void_palace_key_talisman", 8, 140, "文本材料talisman_consume：虚天引路符·瞬发"),
    CAST_TALISMAN_WOODEN_OX("木牛符·瞬发", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "cast_talisman_wooden_ox", 8, 140, "文本材料talisman_consume：木牛符·瞬发"),
    GHOST_KING_SUMMON("鬼王召", SkillCategory.SPELL, Realm.FOUNDATION_ESTABLISHMENT, RealmStage.EARLY, "ghost_king_summon", 12, 220, "文本材料summon：鬼王召"),;

    private final String displayName;
    private final SkillCategory category;
    private final Realm requiredRealm;
    private final RealmStage requiredStage;
    private final String techniqueId;
    private final int spiritualPowerCost;
    private final int cooldownTicks;
    private final String description;
    private final SpiritualRootAttribute[] affinityAttributes;

    SkillType(String displayName, SkillCategory category, Realm requiredRealm, String description, SpiritualRootAttribute... affinityAttributes) {
        this(displayName, category, requiredRealm, null, "", -1, -1, description, affinityAttributes);
    }

    SkillType(String displayName, SkillCategory category, Realm requiredRealm, RealmStage requiredStage, String techniqueId,
              int spiritualPowerCost, int cooldownTicks, String description, SpiritualRootAttribute... affinityAttributes) {
        this.displayName = displayName;
        this.category = category;
        this.requiredRealm = requiredRealm;
        this.requiredStage = requiredStage;
        this.techniqueId = techniqueId;
        this.spiritualPowerCost = spiritualPowerCost;
        this.cooldownTicks = cooldownTicks;
        this.description = description;
        this.affinityAttributes = affinityAttributes;
    }

    public String getDisplayName() { return displayName; }
    public SkillCategory getCategory() { return category; }
    public Realm getRequiredRealm() { return requiredRealm; }
    public RealmStage getRequiredStage() { return requiredStage; }
    public String getTechniqueId() { return techniqueId; }
    public int getConfiguredSpiritualPowerCost() { return spiritualPowerCost; }
    public int getConfiguredCooldownTicks() { return cooldownTicks; }
    public String getDescription() { return description; }
    public SpiritualRootAttribute[] getAffinityAttributes() { return affinityAttributes; }
    public boolean hasAffinityRequirement() { return affinityAttributes.length > 0; }
    public boolean isAutoTechniqueSkill() { return techniqueId != null && !techniqueId.isBlank(); }
    public boolean isPhase4QiSkill() { return isAutoTechniqueSkill(); }
}
