package com.xunxian.seekingimmortals.client.ui;

import com.xunxian.seekingimmortals.client.UiClimate;

/**
 * Player-selectable UI theme layer above the {@link InkScene} scene system.
 *
 * <p>Scenes stay semantic (screen meaning picks QUIET_STUDY/FIELD_NOTES/
 * LEDGER_HALL/OMEN_RED); the theme decides which 46-token palette each scene
 * resolves to. {@link #INKSCROLL} is the shipped 云笈墨卷 baseline and simply
 * delegates to the palettes stored on {@link InkScene}; the other themes embed
 * the expanded palettes generated by {@code scripts/expand_theme_palettes.py} —
 * five from the prototype docs under {@code project_docs/ui_prototypes/} and a
 * second batch drawn from 《凡人修仙传》 imagery (掌天瓶/血色禁地/黄枫谷/青元剑光/噬金虫).</p>
 *
 * <p>Headless-safe: class initialization only builds color records and never
 * touches Minecraft/Forge classes; persistence lives in {@link UiThemeConfig}.</p>
 */
public enum UiTheme {
    /** 云笈墨卷 — baseline ink-on-paper scroll (delegates to InkScene). */
    INKSCROLL("inkscroll", null, null, null, null),

    /** 玄夜星图 — night star-chart, deep indigo with starlight accents. */
    NIGHT_STARCHART("night_starchart",
            new UiClimate.Palette(
                    0xFF6FA8C8, 0x884E768C, 0xE80A0E13, 0xF2101820, 0xEE232A32, 0xF00E141B,
                    0x1E6FA8C8, 0x3A6FA8C8, 0x5585B5D0, 0x12606060,
                    0xF02D343B, 0xF040464D, 0xDD0D131A, 0xF04C5258,
                    0xFF6FA8C8, 0xFFA1C6DB, 0xFFD8E4EC, 0xFF8C9499,
                    0xFF7AB8C0, 0xFFB04838, 0xFFDC7050, 0xFFC8A050,
                    0xFF0E141B, 0x336FA8C8, 0xFF283848, 0xFF203040,
                    0xFF282F36, 0xFF424B53, 0x556FA8C8, 0x660A1015,
                    0xCC6FA8C8, 0xEE9AC2D8, 0x1AFFFFFF, 0x44070B0E, 0x668CB9D3,
                    0xC86FA8C8, 0xD8101820, 0xD0232A32, 0x884E768C,
                    0xC02D343B, 0x5E101820,
                    0x906FA8C8, 0x52101820, 0x44232A32, 0x8C2D343B, 0x38101820,
                    UiClimate.Material.JADE),
            new UiClimate.Palette(
                    0xFF9AB8C0, 0x886C8186, 0xE80B0D12, 0xF212161E, 0xEE252930, 0xF00F131A,
                    0x1E9AB8C0, 0x3A9AB8C0, 0x55A9C3C9, 0x12606060,
                    0xF02E3239, 0xF041454B, 0xDD0E1218, 0xF04D5056,
                    0xFF9AB8C0, 0xFFBDD1D6, 0xFFDCE0D8, 0xFF8F928C,
                    0xFF7AB8C0, 0xFFB04838, 0xFFDC7050, 0xFFC8A050,
                    0xFF0F131A, 0x339AB8C0, 0xFF283848, 0xFF203040,
                    0xFF2A2D34, 0xFF44484C, 0x559AB8C0, 0x660C0E14,
                    0xCC9AB8C0, 0xEEB8CDD3, 0x1AFFFFFF, 0x44080A0D, 0x66AEC6CD,
                    0xC89AB8C0, 0xD812161E, 0xD0252930, 0x886C8186,
                    0xC02E3239, 0x5E12161E,
                    0x909AB8C0, 0x5212161E, 0x44252930, 0x8C2E3239, 0x3812161E,
                    UiClimate.Material.BAMBOO),
            new UiClimate.Palette(
                    0xFFC8A050, 0x888C7038, 0xE8100C12, 0xF21A141E, 0xEE2C2730, 0xF016111A,
                    0x1EC8A050, 0x3AC8A050, 0x55D0AE6A, 0x12606060,
                    0xF0353039, 0xF048434B, 0xDD151018, 0xF0534F56,
                    0xFFC8A050, 0xFFDBC18D, 0xFFE4D8C8, 0xFF948C82,
                    0xFF7AB8C0, 0xFFB04838, 0xFFDC7050, 0xFFC8A050,
                    0xFF16111A, 0x33C8A050, 0xFF283848, 0xFF203040,
                    0xFF312C34, 0xFF4C4548, 0x55C8A050, 0x66110D14,
                    0xCCC8A050, 0xEED8BC84, 0x1AFFFFFF, 0x440C090D, 0x66D3B373,
                    0xC8C8A050, 0xD81A141E, 0xD02C2730, 0x888C7038,
                    0xC0353039, 0x5E1A141E,
                    0x90C8A050, 0x521A141E, 0x442C2730, 0x8C353039, 0x381A141E,
                    UiClimate.Material.LACQUER),
            new UiClimate.Palette(
                    0xFFC84838, 0x888C3227, 0xE8120A0B, 0xF21E1012, 0xEE302325, 0xF01A0E0F,
                    0x1EC84838, 0x3AC84838, 0x55D06356, 0x12606060,
                    0xF0392D2E, 0xF04B4041, 0xDD180D0E, 0xF0564C4D,
                    0xFFC84838, 0xFFDB887E, 0xFFE8D0C8, 0xFF978782,
                    0xFF7AB8C0, 0xFFB04838, 0xFFDC7050, 0xFFC8A050,
                    0xFF1A0E0F, 0x33C84838, 0xFF283848, 0xFF203040,
                    0xFF34282A, 0xFF504040, 0x55C84838, 0x66140A0C,
                    0xCCC84838, 0xEED87F74, 0x1AFFFFFF, 0x440D0708, 0x66D36D60,
                    0xC8C84838, 0xD81E1012, 0xD0302325, 0x888C3227,
                    0xC0392D2E, 0x5E1E1012,
                    0x90C84838, 0x521E1012, 0x44302325, 0x8C392D2E, 0x381E1012,
                    UiClimate.Material.SEAL)),

    /** 青铜鼎彝 — bronze tripod, patina green with inlaid gold. */
    BRONZE_TRIPOD("bronze_tripod",
            new UiClimate.Palette(
                    0xFF5A9078, 0x883F6554, 0xE80D1311, 0xF216201C, 0xEE29322E, 0xF0131B18,
                    0x1E5A9078, 0x3A5A9078, 0x5573A18C, 0x12606060,
                    0xF0323B37, 0xF0454D49, 0xDD121A16, 0xF0505855,
                    0xFF5A9078, 0xFF94B7A7, 0xFFE0E0D0, 0xFF929287,
                    0xFF6E9C94, 0xFFB44030, 0xFFDC6848, 0xFFC89848,
                    0xFF131B18, 0x335A9078, 0xFF384840, 0xFF304038,
                    0xFF2D3633, 0xFF485049, 0x555A9078, 0x660E1512,
                    0xCC5A9078, 0xEE8CB1A0, 0x1AFFFFFF, 0x440A0E0D, 0x667BA693,
                    0xC85A9078, 0xD816201C, 0xD029322E, 0x883F6554,
                    0xC0323B37, 0x5E16201C,
                    0x905A9078, 0x5216201C, 0x4429322E, 0x8C323B37, 0x3816201C,
                    UiClimate.Material.JADE),
            new UiClimate.Palette(
                    0xFF6E9060, 0x884D6543, 0xE810110D, 0xF21A1C16, 0xEE2C2E29, 0xF0161813,
                    0x1E6E9060, 0x3A6E9060, 0x5584A178, 0x12606060,
                    0xF0353732, 0xF0484945, 0xDD151612, 0xF0535550,
                    0xFF6E9060, 0xFFA1B798, 0xFFE2DEC8, 0xFF939082,
                    0xFF6E9C94, 0xFFB44030, 0xFFDC6848, 0xFFC89848,
                    0xFF161813, 0x336E9060, 0xFF384840, 0xFF304038,
                    0xFF31332D, 0xFF4C4C42, 0x556E9060, 0x6611120E,
                    0xCC6E9060, 0xEE9AB190, 0x1AFFFFFF, 0x440C0D0A, 0x668BA680,
                    0xC86E9060, 0xD81A1C16, 0xD02C2E29, 0x884D6543,
                    0xC0353732, 0x5E1A1C16,
                    0x906E9060, 0x521A1C16, 0x442C2E29, 0x8C353732, 0x381A1C16,
                    UiClimate.Material.BAMBOO),
            new UiClimate.Palette(
                    0xFFC89848, 0x888C6A32, 0xE8130E0C, 0xF2201814, 0xEE322A27, 0xF01B1411,
                    0x1EC89848, 0x3AC89848, 0x55D0A763, 0x12606060,
                    0xF03B3430, 0xF04D4643, 0xDD1A1310, 0xF058524F,
                    0xFFC89848, 0xFFDBBC88, 0xFFECDEC0, 0xFF99907D,
                    0xFF6E9C94, 0xFFB44030, 0xFFDC6848, 0xFFC89848,
                    0xFF1B1411, 0x33C89848, 0xFF384840, 0xFF304038,
                    0xFF362F2C, 0xFF534A3F, 0x55C89848, 0x6615100D,
                    0xCCC89848, 0xEED8B77F, 0x1AFFFFFF, 0x440E0B09, 0x66D3AD6D,
                    0xC8C89848, 0xD8201814, 0xD0322A27, 0x888C6A32,
                    0xC03B3430, 0x5E201814,
                    0x90C89848, 0x52201814, 0x44322A27, 0x8C3B3430, 0x38201814,
                    UiClimate.Material.LACQUER),
            new UiClimate.Palette(
                    0xFFB44030, 0x887E2D22, 0xE8120B0A, 0xF21E1210, 0xEE302523, 0xF01A0F0E,
                    0x1EB44030, 0x3AB44030, 0x55BF5D4F, 0x12606060,
                    0xF0392E2D, 0xF04B4140, 0xDD180E0D, 0xF0564D4C,
                    0xFFB44030, 0xFFCE8378, 0xFFE8D4C8, 0xFF978A82,
                    0xFF6E9C94, 0xFFB44030, 0xFFDC6848, 0xFFC89848,
                    0xFF1A0F0E, 0x33B44030, 0xFF384840, 0xFF304038,
                    0xFF342A28, 0xFF50423E, 0x55B44030, 0x66140C0A,
                    0xCCB44030, 0xEECA796E, 0x1AFFFFFF, 0x440D0807, 0x66C36659,
                    0xC8B44030, 0xD81E1210, 0xD0302523, 0x887E2D22,
                    0xC0392E2D, 0x5E1E1210,
                    0x90B44030, 0x521E1210, 0x44302523, 0x8C392E2D, 0x381E1210,
                    UiClimate.Material.SEAL)),

    /** 洞府石刻 — cave inscription, mid-tone stone with moss and lamplight. */
    CAVE_INSCRIPTION("cave_inscription",
            new UiClimate.Palette(
                    0xFF6A9070, 0x884A654E, 0xE8191C1A, 0xF22A2E2C, 0xEE3B3F3D, 0xF0242725,
                    0x1E6A9070, 0x3A6A9070, 0x5580A185, 0x12606060,
                    0xF0444745, 0xF0555856, 0xDD222523, 0xF05F6261,
                    0xFF6A9070, 0xFF9EB7A2, 0xFFD8DCD4, 0xFF8C8F8A,
                    0xFF6E9C94, 0xFFB44430, 0xFFDC6C48, 0xFFC89850,
                    0xFF242725, 0x336A9070, 0xFF484034, 0xFF40382C,
                    0xFF3F4341, 0xFF565A56, 0x556A9070, 0x661B1E1D,
                    0xCC6A9070, 0xEE97B19B, 0x20FFFFFF, 0x44131514, 0x6688A68D,
                    0xC86A9070, 0xD82A2E2C, 0xD03B3F3D, 0x884A654E,
                    0xC0444745, 0x5E2A2E2C,
                    0x906A9070, 0x522A2E2C, 0x443B3F3D, 0x8C444745, 0x382A2E2C,
                    UiClimate.Material.JADE),
            new UiClimate.Palette(
                    0xFFA08850, 0x88705F38, 0xE81D1C18, 0xF2302E28, 0xEE413F39, 0xF0292722,
                    0x1EA08850, 0x3AA08850, 0x55AE9A6A, 0x12606060,
                    0xF0494742, 0xF0595853, 0xDD262520, 0xF064625E,
                    0xFFA08850, 0xFFC1B28D, 0xFFDCD8CC, 0xFF8F8C85,
                    0xFF6E9C94, 0xFFB44430, 0xFFDC6C48, 0xFFC89850,
                    0xFF292722, 0x33A08850, 0xFF484034, 0xFF40382C,
                    0xFF45433E, 0xFF5B5851, 0x55A08850, 0x661F1E1A,
                    0xCCA08850, 0xEEBCAC84, 0x20FFFFFF, 0x44161512, 0x66B3A073,
                    0xC8A08850, 0xD8302E28, 0xD0413F39, 0x88705F38,
                    0xC0494742, 0x5E302E28,
                    0x90A08850, 0x52302E28, 0x44413F39, 0x8C494742, 0x38302E28,
                    UiClimate.Material.BAMBOO),
            new UiClimate.Palette(
                    0xFFC08040, 0x88865A2D, 0xE81F1A16, 0xF2342C24, 0xEE443D36, 0xF02C251F,
                    0x1EC08040, 0x3AC08040, 0x55C9935D, 0x12606060,
                    0xF04C453E, 0xF05D5650, 0xDD2A231D, 0xF067615B,
                    0xFFC08040, 0xFFD6AC83, 0xFFE4D8C4, 0xFF948C7F,
                    0xFF6E9C94, 0xFFB44430, 0xFFDC6C48, 0xFFC89850,
                    0xFF2C251F, 0x33C08040, 0xFF484034, 0xFF40382C,
                    0xFF48413A, 0xFF60574C, 0x55C08040, 0x66221D17,
                    0xCCC08040, 0xEED3A679, 0x20FFFFFF, 0x44171410, 0x66CD9966,
                    0xC8C08040, 0xD8342C24, 0xD0443D36, 0x88865A2D,
                    0xC04C453E, 0x5E342C24,
                    0x90C08040, 0x52342C24, 0x44443D36, 0x8C4C453E, 0x38342C24,
                    UiClimate.Material.LACQUER),
            new UiClimate.Palette(
                    0xFFC05030, 0x88863822, 0xE8221412, 0xF238221E, 0xEE483430, 0xF0301D1A,
                    0x1EC05030, 0x3AC05030, 0x55C96A4F, 0x12606060,
                    0xF0503D39, 0xF0604E4B, 0xDD2D1B18, 0xF06A5956,
                    0xFFC05030, 0xFFD68D78, 0xFFE6D2C6, 0xFF968881,
                    0xFF6E9C94, 0xFFB44430, 0xFFDC6C48, 0xFFC89850,
                    0xFF301D1A, 0x33C05030, 0xFF484034, 0xFF40382C,
                    0xFF4C3834, 0xFF644E48, 0x55C05030, 0x66241614,
                    0xCCC05030, 0xEED3846E, 0x20FFFFFF, 0x44190F0D, 0x66CD7359,
                    0xC8C05030, 0xD838221E, 0xD0483430, 0x88863822,
                    0xC0503D39, 0x5E38221E,
                    0x90C05030, 0x5238221E, 0x44483430, 0x8C503D39, 0x3838221E,
                    UiClimate.Material.SEAL)),

    /** 符箓黄纸 — talisman paper, bright yellow paper with cinnabar lines. */
    TALISMAN_PAPER("talisman_paper",
            new UiClimate.Palette(
                    0xFF3A5A78, 0x88293F54, 0xC88F8A76, 0xF2EEE6C4, 0xEEF3EED6, 0xF0E0D8B8,
                    0x1F3A5A78, 0x3D3A5A78, 0x6158738C, 0x0F837F6C,
                    0xF0E2DABA, 0xF0D6CFB0, 0xDDBEB89D, 0xF0F6F1DF,
                    0xFF3A5A78, 0xFF2C445A, 0xFF2A3028, 0xFF787966,
                    0xFF3A6A72, 0xFF9E3226, 0xFFC05038, 0xFF9A7020,
                    0xFFD6CFB0, 0x333A5A78, 0xFF7A4638, 0xFF8E4A3A,
                    0xFFD1CAAC, 0xFFBDB89D, 0x553A5A78, 0x669B967F,
                    0xCC3A5A78, 0xEE758CA0, 0x2AFFFFFF, 0x386B6758, 0x66617B93,
                    0xC83A5A78, 0xD8EEE6C4, 0xD0F3EED6, 0x88293F54,
                    0xC0E2DABA, 0x5EEEE6C4,
                    0x903A5A78, 0x52EEE6C4, 0x44F3EED6, 0x8CE2DABA, 0x38EEE6C4,
                    UiClimate.Material.JADE),
            new UiClimate.Palette(
                    0xFFA83828, 0x8876271C, 0xC890896E, 0xF2F0E4B8, 0xEEF4ECCD, 0xF0E2D6AD,
                    0x1FA83828, 0x3DA83828, 0x61B55648, 0x0F847D65,
                    0xF0E4D9AF, 0xF0D8CDA6, 0xDDC0B693, 0xF0F7F0D8,
                    0xFFA83828, 0xFF7E2A1E, 0xFF302A20, 0xFF7D745D,
                    0xFF3A6A72, 0xFF9E3226, 0xFFC05038, 0xFF9A7020,
                    0xFFD8CDA6, 0x33A83828, 0xFF7A4638, 0xFF8E4A3A,
                    0xFFD3C9A2, 0xFFC0B692, 0x55A83828, 0x669C9478,
                    0xCCA83828, 0xEEC27468, 0x2AFFFFFF, 0x386C6753, 0x66B96053,
                    0xC8A83828, 0xD8F0E4B8, 0xD0F4ECCD, 0x8876271C,
                    0xC0E4D9AF, 0x5EF0E4B8,
                    0x90A83828, 0x52F0E4B8, 0x44F4ECCD, 0x8CE4D9AF, 0x38F0E4B8,
                    UiClimate.Material.BAMBOO),
            new UiClimate.Palette(
                    0xFFB07828, 0x887B541C, 0xC88B8260, 0xF2E8D8A0, 0xEEEFE4BC, 0xF0DACB96,
                    0x1FB07828, 0x3DB07828, 0x61BC8C48, 0x0F807758,
                    0xF0DCCD98, 0xF0D1C290, 0xDDBAAD80, 0xF0F2EACB,
                    0xFFB07828, 0xFF845A1E, 0xFF342C1C, 0xFF7C7151,
                    0xFF3A6A72, 0xFF9E3226, 0xFFC05038, 0xFF9A7020,
                    0xFFD1C290, 0x33B07828, 0xFF7A4638, 0xFF8E4A3A,
                    0xFFCCBE8D, 0xFFBBAD7F, 0x55B07828, 0x66978C68,
                    0xCCB07828, 0xEEC8A068, 0x2AFFFFFF, 0x38686148, 0x66C09353,
                    0xC8B07828, 0xD8E8D8A0, 0xD0EFE4BC, 0x887B541C,
                    0xC0DCCD98, 0x5EE8D8A0,
                    0x90B07828, 0x52E8D8A0, 0x44EFE4BC, 0x8CDCCD98, 0x38E8D8A0,
                    UiClimate.Material.LACQUER),
            new UiClimate.Palette(
                    0xFFC03020, 0x88862216, 0xC88E846A, 0xF2ECDCB0, 0xEEF2E6C8, 0xF0DECFA5,
                    0x1FC03020, 0x3DC03020, 0x61C94F41, 0x0F827961,
                    0xF0E0D1A7, 0xF0D4C69E, 0xDDBDB08D, 0xF0F5ECD4,
                    0xFFC03020, 0xFF902418, 0xFF362418, 0xFF7F6E55,
                    0xFF3A6A72, 0xFF9E3226, 0xFFC05038, 0xFF9A7020,
                    0xFFD4C69E, 0x33C03020, 0xFF7A4638, 0xFF8E4A3A,
                    0xFFD0C29B, 0xFFBEAE8A, 0x55C03020, 0x66998F72,
                    0xCCC03020, 0xEED36E63, 0x2AFFFFFF, 0x386A634F, 0x66CD594D,
                    0xC8C03020, 0xD8ECDCB0, 0xD0F2E6C8, 0x88862216,
                    0xC0E0D1A7, 0x5EECDCB0,
                    0x90C03020, 0x52ECDCB0, 0x44F2E6C8, 0x8CE0D1A7, 0x38ECDCB0,
                    UiClimate.Material.SEAL)),

    /** 水墨山水 — ink-wash landscape, pale silk grounds with mineral accents. */
    INKWASH_LANDSCAPE("inkwash_landscape",
            new UiClimate.Palette(
                    0xFF30483C, 0x8822322A, 0xC81A2420, 0xF2E0EAE6, 0xEEE9F0EE, 0xF0D3DCD8,
                    0x1E4A8868, 0x3A4A8868, 0x55659A7F, 0x0F7B817F,
                    0xF0D5DEDA, 0xF0CAD3CF, 0xDDB3BBB8, 0xF0EEF3F1,
                    0xFF4A8868, 0xFF38664E, 0xFF28322E, 0xFF727C78,
                    0xFF3A6A72, 0xFF9E3226, 0xFFC05038, 0xFF9A7020,
                    0xFFCAD3CF, 0x334A8868, 0xFF7A4638, 0xFF8E4A3A,
                    0xFFC5CECA, 0xFFB2BCB8, 0x5530483C, 0x66929896,
                    0xCC4A8868, 0xEE80AC95, 0x30FFFFFF, 0x38656967, 0x66596D63,
                    0xC830483C, 0xD8E0EAE6, 0xD0E9F0EE, 0x8822322A,
                    0xC0D5DEDA, 0x5EE0EAE6,
                    0x9030483C, 0x52E0EAE6, 0x44E9F0EE, 0x8CD5DEDA, 0x38E0EAE6,
                    UiClimate.Material.JADE),
            new UiClimate.Palette(
                    0xFF343D3E, 0x88242B2B, 0xC81A2420, 0xF2EAE8DA, 0xEEF0EFE5, 0xF0DCDACD,
                    0x1E3E6A88, 0x3A3E6A88, 0x555B809A, 0x0F818078,
                    0xF0DEDCCF, 0xF0D3D1C4, 0xDDBBBAAE, 0xF0F3F2EB,
                    0xFF3E6A88, 0xFF2E5066, 0xFF302E26, 0xFF7A786E,
                    0xFF3A6A72, 0xFF9E3226, 0xFFC05038, 0xFF9A7020,
                    0xFFD3D1C4, 0x333E6A88, 0xFF7A4638, 0xFF8E4A3A,
                    0xFFCECCC0, 0xFFBCBAAD, 0x55343D3E, 0x6698978E,
                    0xCC3E6A88, 0xEE7897AC, 0x30FFFFFF, 0x38696862, 0x665D6465,
                    0xC8343D3E, 0xD8EAE8DA, 0xD0F0EFE5, 0x88242B2B,
                    0xC0DEDCCF, 0x5EEAE8DA,
                    0x90343D3E, 0x52EAE8DA, 0x44F0EFE5, 0x8CDEDCCF, 0x38EAE8DA,
                    UiClimate.Material.BAMBOO),
            new UiClimate.Palette(
                    0xFF51402A, 0x88392D1D, 0xC81A2420, 0xF2E8DFC2, 0xEEEFE9D4, 0xF0DAD2B6,
                    0x1EA87848, 0x3AA87848, 0x55B58C63, 0x0F807B6B,
                    0xF0DCD4B8, 0xF0D1C9AF, 0xDDBAB29B, 0xF0F2EDDD,
                    0xFFA87848, 0xFF7E5A36, 0xFF342E20, 0xFF7C7561,
                    0xFF3A6A72, 0xFF9E3226, 0xFFC05038, 0xFF9A7020,
                    0xFFD1C9AF, 0x33A87848, 0xFF7A4638, 0xFF8E4A3A,
                    0xFFCCC4AB, 0xFFBBB39A, 0x5551402A, 0x6697917E,
                    0xCCA87848, 0xEEC2A07F, 0x30FFFFFF, 0x38686457, 0x66746655,
                    0xC851402A, 0xD8E8DFC2, 0xD0EFE9D4, 0x88392D1D,
                    0xC0DCD4B8, 0x5EE8DFC2,
                    0x9051402A, 0x52E8DFC2, 0x44EFE9D4, 0x8CDCD4B8, 0x38E8DFC2,
                    UiClimate.Material.LACQUER),
            new UiClimate.Palette(
                    0xFF512D26, 0x88391F1B, 0xC81A2420, 0xF2E6DED6, 0xEEEEE8E2, 0xF0D8D1C9,
                    0x1EA83C30, 0x3AA83C30, 0x55B5594F, 0x0F7F7A76,
                    0xF0DAD3CB, 0xF0CFC8C1, 0xDDB8B2AB, 0xF0F1EDE8,
                    0xFFA83C30, 0xFF7E2D24, 0xFF342822, 0xFF7B716A,
                    0xFF3A6A72, 0xFF9E3226, 0xFFC05038, 0xFF9A7020,
                    0xFFCFC8C1, 0x33A83C30, 0xFF7A4638, 0xFF8E4A3A,
                    0xFFCAC3BC, 0xFFBAB0A9, 0x55512D26, 0x6696908B,
                    0xCCA83C30, 0xEEC2766E, 0x30FFFFFF, 0x38676460, 0x66745751,
                    0xC8512D26, 0xD8E6DED6, 0xD0EEE8E2, 0x88391F1B,
                    0xC0DAD3CB, 0x5EE6DED6,
                    0x90512D26, 0x52E6DED6, 0x44EEE8E2, 0x8CDAD3CB, 0x38E6DED6,
                    UiClimate.Material.SEAL)),

    /** 掌天瓶露 — the mystic vial's green dew, bottle-dark ground with emerald drip glow. */
    MYSTIC_VIAL("mystic_vial",
            new UiClimate.Palette(
                    0xFF56A878, 0x883C7654, 0xE808110D, 0xF20E1C16, 0xEE212E29, 0xF00C1813,
                    0x1E56A878, 0x3A56A878, 0x556FB58C, 0x12606060, 0xF02B3732, 0xF03E4945,
                    0xDD0B1612, 0xF04A5550, 0xFF56A878, 0xFF91C6A7, 0xFFD4E8DA, 0xFF8A978E,
                    0xFF7AC096, 0xFFB04434, 0xFFDC6C4C, 0xFFC0A048, 0xFF0C1813, 0x3356A878,
                    0xFF223428, 0xFF1A2C20, 0xFF26332D, 0xFF404F47, 0x5556A878, 0x6609120E,
                    0xCC56A878, 0xEE89C2A0, 0x1AFFFFFF, 0x44060D0A, 0x6678B993, 0xC856A878,
                    0xD80E1C16, 0xD0212E29, 0x883C7654, 0xC02B3732, 0x5E0E1C16, 0x9056A878,
                    0x520E1C16, 0x44212E29, 0x8C2B3732, 0x380E1C16,
                    UiClimate.Material.JADE),
            new UiClimate.Palette(
                    0xFF78A860, 0x88547643, 0xE80A120C, 0xF2101E14, 0xEE233027, 0xF00E1A11,
                    0x1E78A860, 0x3A78A860, 0x558CB578, 0x12606060, 0xF02D3930, 0xF0404B43,
                    0xDD0D1810, 0xF04C564F, 0xFF78A860, 0xFFA7C698, 0xFFD8E4D0, 0xFF8C9487,
                    0xFF7AC096, 0xFFB04434, 0xFFDC6C4C, 0xFFC0A048, 0xFF0E1A11, 0x3378A860,
                    0xFF223428, 0xFF1A2C20, 0xFF28342C, 0xFF425043, 0x5578A860, 0x660A140D,
                    0xCC78A860, 0xEEA0C290, 0x1AFFFFFF, 0x44070D09, 0x6693B980, 0xC878A860,
                    0xD8101E14, 0xD0233027, 0x88547643, 0xC02D3930, 0x5E101E14, 0x9078A860,
                    0x52101E14, 0x44233027, 0x8C2D3930, 0x38101E14,
                    UiClimate.Material.BAMBOO),
            new UiClimate.Palette(
                    0xFFB0A050, 0x887B7038, 0xE80D1310, 0xF216201A, 0xEE29322C, 0xF0131B16,
                    0x1EB0A050, 0x3AB0A050, 0x55BCAE6A, 0x12606060, 0xF0323B35, 0xF0454D48,
                    0xDD121A15, 0xF0505853, 0xFFB0A050, 0xFFCCC18D, 0xFFE0DEC4, 0xFF92907F,
                    0xFF7AC096, 0xFFB04434, 0xFFDC6C4C, 0xFFC0A048, 0xFF131B16, 0x33B0A050,
                    0xFF223428, 0xFF1A2C20, 0xFF2D3631, 0xFF485044, 0x55B0A050, 0x660E1511,
                    0xCCB0A050, 0xEEC8BC84, 0x1AFFFFFF, 0x440A0E0C, 0x66C0B373, 0xC8B0A050,
                    0xD816201A, 0xD029322C, 0x887B7038, 0xC0323B35, 0x5E16201A, 0x90B0A050,
                    0x5216201A, 0x4429322C, 0x8C323B35, 0x3816201A,
                    UiClimate.Material.LACQUER),
            new UiClimate.Palette(
                    0xFFC04834, 0x88863224, 0xE8100D0C, 0xF21A1614, 0xEE2C2927, 0xF0161311,
                    0x1EC04834, 0x3AC04834, 0x55C96352, 0x12606060, 0xF0353230, 0xF0484543,
                    0xDD151210, 0xF053504F, 0xFFC04834, 0xFFD6887B, 0xFFE6D4C8, 0xFF968A82,
                    0xFF7AC096, 0xFFB04434, 0xFFDC6C4C, 0xFFC0A048, 0xFF161311, 0x33C04834,
                    0xFF223428, 0xFF1A2C20, 0xFF312D2C, 0xFF4D4641, 0x55C04834, 0x66110E0D,
                    0xCCC04834, 0xEED37F71, 0x1AFFFFFF, 0x440C0A09, 0x66CD6D5D, 0xC8C04834,
                    0xD81A1614, 0xD02C2927, 0x88863224, 0xC0353230, 0x5E1A1614, 0x90C04834,
                    0x521A1614, 0x442C2927, 0x8C353230, 0x381A1614,
                    UiClimate.Material.SEAL)),

    /** 血色禁地 — blood trial forbidden grounds, dark crimson mist and veins. */
    BLOOD_TRIAL("blood_trial",
            new UiClimate.Palette(
                    0xFFA85868, 0x88763E49, 0xE813080B, 0xF2200E12, 0xEE322125, 0xF01B0C0F,
                    0x1EA85868, 0x3AA85868, 0x55B5717F, 0x12606060, 0xF03B2B2E, 0xF04D3E41,
                    0xDD1A0B0E, 0xF0584A4D, 0xFFA85868, 0xFFC6929D, 0xFFE8D6D2, 0xFF978B88,
                    0xFF6EA8A0, 0xFFB83830, 0xFFE06048, 0xFFC89848, 0xFF1B0C0F, 0x33A85868,
                    0xFF40262A, 0xFF381E22, 0xFF36262A, 0xFF524042, 0x55A85868, 0x6615090C,
                    0xCCA85868, 0xEEC28A95, 0x1AFFFFFF, 0x440E0608, 0x66B97986, 0xC8A85868,
                    0xD8200E12, 0xD0322125, 0x88763E49, 0xC03B2B2E, 0x5E200E12, 0x90A85868,
                    0x52200E12, 0x44322125, 0x8C3B2B2E, 0x38200E12,
                    UiClimate.Material.JADE),
            new UiClimate.Palette(
                    0xFFB06848, 0x887B4932, 0xE8120B0A, 0xF21E1210, 0xEE302523, 0xF01A0F0E,
                    0x1EB06848, 0x3AB06848, 0x55BC7F63, 0x12606060, 0xF0392E2D, 0xF04B4140,
                    0xDD180E0D, 0xF0564D4C, 0xFFB06848, 0xFFCC9D88, 0xFFE4D8CC, 0xFF948C85,
                    0xFF6EA8A0, 0xFFB83830, 0xFFE06048, 0xFFC89848, 0xFF1A0F0E, 0x33B06848,
                    0xFF40262A, 0xFF381E22, 0xFF342A28, 0xFF50443F, 0x55B06848, 0x66140C0A,
                    0xCCB06848, 0xEEC8957F, 0x1AFFFFFF, 0x440D0807, 0x66C0866D, 0xC8B06848,
                    0xD81E1210, 0xD0302523, 0x887B4932, 0xC0392E2D, 0x5E1E1210, 0x90B06848,
                    0x521E1210, 0x44302523, 0x8C392E2D, 0x381E1210,
                    UiClimate.Material.BAMBOO),
            new UiClimate.Palette(
                    0xFFC08850, 0x88865F38, 0xE8160A0B, 0xF2241012, 0xEE362325, 0xF01F0E0F,
                    0x1EC08850, 0x3AC08850, 0x55C99A6A, 0x12606060, 0xF03E2D2E, 0xF0504041,
                    0xDD1D0D0E, 0xF05B4C4D, 0xFFC08850, 0xFFD6B28D, 0xFFECD8C0, 0xFF998C7D,
                    0xFF6EA8A0, 0xFFB83830, 0xFFE06048, 0xFFC89848, 0xFF1F0E0F, 0x33C08850,
                    0xFF40262A, 0xFF381E22, 0xFF3A282A, 0xFF56423E, 0x55C08850, 0x66170A0C,
                    0xCCC08850, 0xEED3AC84, 0x1AFFFFFF, 0x44100708, 0x66CDA073, 0xC8C08850,
                    0xD8241012, 0xD0362325, 0x88865F38, 0xC03E2D2E, 0x5E241012, 0x90C08850,
                    0x52241012, 0x44362325, 0x8C3E2D2E, 0x38241012,
                    UiClimate.Material.LACQUER),
            new UiClimate.Palette(
                    0xFFCC4030, 0x888F2D22, 0xE8180707, 0xF2280C0C, 0xEE391F1F, 0xF0220A0A,
                    0x1ECC4030, 0x3ACC4030, 0x55D45D4F, 0x12606060, 0xF0422929, 0xF0533D3D,
                    0xDD200A0A, 0xF05E4949, 0xFFCC4030, 0xFFDE8378, 0xFFF0D0C4, 0xFF9C877F,
                    0xFF6EA8A0, 0xFFB83830, 0xFFE06048, 0xFFC89848, 0xFF220A0A, 0x33CC4030,
                    0xFF40262A, 0xFF381E22, 0xFF3E2424, 0xFF5A3D3A, 0x55CC4030, 0x661A0808,
                    0xCCCC4030, 0xEEDB796E, 0x1AFFFFFF, 0x44120505, 0x66D66659, 0xC8CC4030,
                    0xD8280C0C, 0xD0391F1F, 0x888F2D22, 0xC0422929, 0x5E280C0C, 0x90CC4030,
                    0x52280C0C, 0x44391F1F, 0x8C422929, 0x38280C0C,
                    UiClimate.Material.SEAL)),

    /** 黄枫秋色 — Yellow Maple Valley in autumn, warm paper with maple reds. */
    MAPLE_VALLEY("maple_valley",
            new UiClimate.Palette(
                    0xFF7D6D49, 0x88584C33, 0xC8908873, 0xF2F0E2C0, 0xEEF4EBD3, 0xF0E2D4B4,
                    0x1E987830, 0x3A987830, 0x55A78C4F, 0x0F847C6A, 0xF0E4D7B6, 0xF0D8CBAD,
                    0xDDC0B59A, 0xF0F7EFDC, 0xFF987830, 0xFF725A24, 0xFF322A1E, 0xFF7E745F,
                    0xFF3E6E58, 0xFFA03024, 0xFFC25236, 0xFF966E1E, 0xFFD8CBAD, 0x33987830,
                    0xFF7C5030, 0xFF8E5632, 0xFFD3C7A9, 0xFFC0B498, 0x557D6D49, 0x669C937D,
                    0xCC987830, 0xEEB7A06E, 0x2AFFFFFF, 0x386C6656, 0x66978A6D, 0xC87D6D49,
                    0xD8F0E2C0, 0xD0F4EBD3, 0x88584C33, 0xC0E4D7B6, 0x5EF0E2C0, 0x907D6D49,
                    0x52F0E2C0, 0x44F4EBD3, 0x8CE4D7B6, 0x38F0E2C0,
                    UiClimate.Material.JADE),
            new UiClimate.Palette(
                    0xFF856043, 0x885D432F, 0xC88F856C, 0xF2EEDEB4, 0xEEF3E8CA, 0xF0E0D1A9,
                    0x1EB05828, 0x3AB05828, 0x55BC7148, 0x0F837A63, 0xF0E2D3AB, 0xF0D6C8A2,
                    0xDDBEB290, 0xF0F6EDD6, 0xFFB05828, 0xFF84421E, 0xFF342C1C, 0xFF7E7359,
                    0xFF3E6E58, 0xFFA03024, 0xFFC25236, 0xFF966E1E, 0xFFD6C8A2, 0x33B05828,
                    0xFF7C5030, 0xFF8E5632, 0xFFD1C39E, 0xFFC0B28E, 0x55856043, 0x669B9075,
                    0xCCB05828, 0xEEC88A68, 0x2AFFFFFF, 0x386B6451, 0x669D8069, 0xC8856043,
                    0xD8EEDEB4, 0xD0F3E8CA, 0x885D432F, 0xC0E2D3AB, 0x5EEEDEB4, 0x90856043,
                    0x52EEDEB4, 0x44F3E8CA, 0x8CE2D3AB, 0x38EEDEB4,
                    UiClimate.Material.BAMBOO),
            new UiClimate.Palette(
                    0xFF80663B, 0x885A4729, 0xC88B7F62, 0xF2E8D4A4, 0xEEEFE1BF, 0xF0DAC79A,
                    0x1EA87020, 0x3AA87020, 0x55B58541, 0x0F80755A, 0xF0DCC99C, 0xF0D1BF94,
                    0xDDBAAA83, 0xF0F2E7CD, 0xFFA87020, 0xFF7E5418, 0xFF362A18, 0xFF7D6E50,
                    0xFF3E6E58, 0xFFA03024, 0xFFC25236, 0xFF966E1E, 0xFFD1BF94, 0x33A87020,
                    0xFF7C5030, 0xFF8E5632, 0xFFCCBB90, 0xFFBCAA81, 0x5580663B, 0x66978A6B,
                    0xCCA87020, 0xEEC29B63, 0x2AFFFFFF, 0x38685F4A, 0x66998562, 0xC880663B,
                    0xD8E8D4A4, 0xD0EFE1BF, 0x885A4729, 0xC0DCC99C, 0x5EE8D4A4, 0x9080663B,
                    0x52E8D4A4, 0x44EFE1BF, 0x8CDCC99C, 0x38E8D4A4,
                    UiClimate.Material.LACQUER),
            new UiClimate.Palette(
                    0xFF875240, 0x885E392D, 0xC88E826A, 0xF2ECD8B0, 0xEEF2E4C8, 0xF0DECBA5,
                    0x1EB83424, 0x3AB83424, 0x55C35245, 0x0F827761, 0xF0E0CDA7, 0xF0D4C29E,
                    0xDDBDAD8D, 0xF0F5EAD4, 0xFFB83424, 0xFF8A271B, 0xFF38241A, 0xFF806C56,
                    0xFF3E6E58, 0xFFA03024, 0xFFC25236, 0xFF966E1E, 0xFFD4C29E, 0x33B83424,
                    0xFF7C5030, 0xFF8E5632, 0xFFD0BE9B, 0xFFBFAB8A, 0x55875240, 0x66998C72,
                    0xCCB83424, 0xEECD7166, 0x2AFFFFFF, 0x386A614F, 0x669F7566, 0xC8875240,
                    0xD8ECD8B0, 0xD0F2E4C8, 0x885E392D, 0xC0E0CDA7, 0x5EECD8B0, 0x90875240,
                    0x52ECD8B0, 0x44F2E4C8, 0x8CE0CDA7, 0x38ECD8B0,
                    UiClimate.Material.SEAL)),

    /** 青元剑光 — azure sword light, pale cyan silk with sweeping sword streaks. */
    AZURE_SWORD("azure_sword",
            new UiClimate.Palette(
                    0xFF576E76, 0x883D4D53, 0xC8858C8E, 0xF2DEEAEC, 0xEEE8F0F2, 0xF0D1DCDE,
                    0x1E3E7488, 0x3A3E7488, 0x555B899A, 0x0F7A8182, 0xF0D3DEE0, 0xF0C8D3D4,
                    0xDDB2BBBD, 0xF0EDF3F5, 0xFF3E7488, 0xFF2E5766, 0xFF26323A, 0xFF707C81,
                    0xFF386E78, 0xFF9E3428, 0xFFC0543A, 0xFF987222, 0xFFC8D3D4, 0x333E7488,
                    0xFF3C5A5C, 0xFF345254, 0xFFC3CED0, 0xFFB0BCC0, 0x55576E76, 0x66909899,
                    0xCC3E7488, 0xEE789EAC, 0x2AFFFFFF, 0x3864696A, 0x66798B91, 0xC8576E76,
                    0xD8DEEAEC, 0xD0E8F0F2, 0x883D4D53, 0xC0D3DEE0, 0x5EDEEAEC, 0x90576E76,
                    0x52DEEAEC, 0x44E8F0F2, 0x8CD3DEE0, 0x38DEEAEC,
                    UiClimate.Material.JADE),
            new UiClimate.Palette(
                    0xFF5C766F, 0x8840534E, 0xC8888E89, 0xF2E2ECE4, 0xEEEBF2EC, 0xF0D4DED6,
                    0x1E48887C, 0x3A48887C, 0x55639A90, 0x0F7C827D, 0xF0D7E0D9, 0xF0CBD4CD,
                    0xDDB5BDB6, 0xF0EFF5F0, 0xFF48887C, 0xFF36665D, 0xFF2A342C, 0xFF747E76,
                    0xFF386E78, 0xFF9E3428, 0xFFC0543A, 0xFF987222, 0xFFCBD4CD, 0x3348887C,
                    0xFF3C5A5C, 0xFF345254, 0xFFC7D0C9, 0xFFB4BEB6, 0x555C766F, 0x66939994,
                    0xCC48887C, 0xEE7FACA3, 0x2AFFFFFF, 0x38666A67, 0x667D918C, 0xC85C766F,
                    0xD8E2ECE4, 0xD0EBF2EC, 0x8840534E, 0xC0D7E0D9, 0x5EE2ECE4, 0x905C766F,
                    0x52E2ECE4, 0x44EBF2EC, 0x8CD7E0D9, 0x38E2ECE4,
                    UiClimate.Material.BAMBOO),
            new UiClimate.Palette(
                    0xFF746E51, 0x88514D39, 0xC88A897D, 0xF2E6E4D0, 0xEEEEECDE, 0xF0D8D6C4,
                    0x1E8A7838, 0x3A8A7838, 0x559C8C56, 0x0F7F7D72, 0xF0DAD9C6, 0xF0CFCDBB,
                    0xDDB8B6A6, 0xF0F1F0E5, 0xFF8A7838, 0xFF685A2A, 0xFF322F20, 0xFF7A7766,
                    0xFF386E78, 0xFF9E3428, 0xFFC0543A, 0xFF987222, 0xFFCFCDBB, 0x338A7838,
                    0xFF3C5A5C, 0xFF345254, 0xFFCAC9B7, 0xFFB9B7A4, 0x55746E51, 0x66969487,
                    0xCC8A7838, 0xEEADA074, 0x2AFFFFFF, 0x3867675E, 0x66908B74, 0xC8746E51,
                    0xD8E6E4D0, 0xD0EEECDE, 0x88514D39, 0xC0DAD9C6, 0x5EE6E4D0, 0x90746E51,
                    0x52E6E4D0, 0x44EEECDE, 0x8CDAD9C6, 0x38E6E4D0,
                    UiClimate.Material.LACQUER),
            new UiClimate.Palette(
                    0xFF7C5853, 0x88573E3A, 0xC8898583, 0xF2E4DEDA, 0xEEECE8E5, 0xF0D6D1CD,
                    0x1EA04034, 0x3AA04034, 0x55AE5D52, 0x0F7D7A78, 0xF0D9D3CF, 0xF0CDC8C4,
                    0xDDB6B2AE, 0xF0F0EDEB, 0xFFA04034, 0xFF783027, 0xFF342826, 0xFF7A716E,
                    0xFF386E78, 0xFF9E3428, 0xFFC0543A, 0xFF987222, 0xFFCDC8C4, 0x33A04034,
                    0xFF3C5A5C, 0xFF345254, 0xFFC9C3C0, 0xFFB8B0AD, 0x557C5853, 0x6694908E,
                    0xCCA04034, 0xEEBC7971, 0x2AFFFFFF, 0x38676462, 0x66967975, 0xC87C5853,
                    0xD8E4DEDA, 0xD0ECE8E5, 0x88573E3A, 0xC0D9D3CF, 0x5EE4DEDA, 0x907C5853,
                    0x52E4DEDA, 0x44ECE8E5, 0x8CD9D3CF, 0x38E4DEDA,
                    UiClimate.Material.SEAL)),

    /** 噬金虫甲 — gold-devourer chitin, lacquer-black shell with gold flecks. */
    GOLD_BEETLE("gold_beetle",
            new UiClimate.Palette(
                    0xFF9098A8, 0x88656A76, 0xE80D0C10, 0xF216141A, 0xEE29272C, 0xF0131116,
                    0x1E9098A8, 0x3A9098A8, 0x55A1A7B5, 0x12606060, 0xF0323035, 0xF0454348,
                    0xDD121015, 0xF0504F53, 0xFF9098A8, 0xFFB7BCC6, 0xFFE0DCE8, 0xFF928F97,
                    0xFF7AA888, 0xFFB24230, 0xFFDC6A46, 0xFFCCA040, 0xFF131116, 0x339098A8,
                    0xFF363024, 0xFF2E281E, 0xFF2D2C31, 0xFF48464E, 0x559098A8, 0x660E0D11,
                    0xCC9098A8, 0xEEB1B7C2, 0x1AFFFFFF, 0x440A090C, 0x66A6ADB9, 0xC89098A8,
                    0xD816141A, 0xD029272C, 0x88656A76, 0xC0323035, 0x5E16141A, 0x909098A8,
                    0x5216141A, 0x4429272C, 0x8C323035, 0x3816141A,
                    UiClimate.Material.JADE),
            new UiClimate.Palette(
                    0xFFA89048, 0x88766532, 0xE80E0D0A, 0xF2181610, 0xEE2A2923, 0xF014130E,
                    0x1EA89048, 0x3AA89048, 0x55B5A163, 0x12606060, 0xF034322D, 0xF0464540,
                    0xDD13120D, 0xF052504C, 0xFFA89048, 0xFFC6B788, 0xFFE4E0CC, 0xFF949285,
                    0xFF7AA888, 0xFFB24230, 0xFFDC6A46, 0xFFCCA040, 0xFF14130E, 0x33A89048,
                    0xFF363024, 0xFF2E281E, 0xFF2F2D28, 0xFF4B483F, 0x55A89048, 0x66100E0A,
                    0xCCA89048, 0xEEC2B17F, 0x1AFFFFFF, 0x440B0A07, 0x66B9A66D, 0xC8A89048,
                    0xD8181610, 0xD02A2923, 0x88766532, 0xC034322D, 0x5E181610, 0x90A89048,
                    0x52181610, 0x442A2923, 0x8C34322D, 0x38181610,
                    UiClimate.Material.BAMBOO),
            new UiClimate.Palette(
                    0xFFC89838, 0x888C6A27, 0xE8110D08, 0xF21C160E, 0xEE2E2921, 0xF018130C,
                    0x1EC89838, 0x3AC89838, 0x55D0A756, 0x12606060, 0xF037322B, 0xF049453E,
                    0xDD16120B, 0xF055504A, 0xFFC89838, 0xFFDBBC7E, 0xFFECDEBC, 0xFF99907A,
                    0xFF7AA888, 0xFFB24230, 0xFFDC6A46, 0xFFCCA040, 0xFF18130C, 0x33C89838,
                    0xFF363024, 0xFF2E281E, 0xFF332D26, 0xFF50483A, 0x55C89838, 0x66120E09,
                    0xCCC89838, 0xEED8B774, 0x1AFFFFFF, 0x440D0A06, 0x66D3AD60, 0xC8C89838,
                    0xD81C160E, 0xD02E2921, 0x888C6A27, 0xC037322B, 0x5E1C160E, 0x90C89838,
                    0x521C160E, 0x442E2921, 0x8C37322B, 0x381C160E,
                    UiClimate.Material.LACQUER),
            new UiClimate.Palette(
                    0xFFC04838, 0x88863227, 0xE8110A0A, 0xF21C1010, 0xEE2E2323, 0xF0180E0E,
                    0x1EC04838, 0x3AC04838, 0x55C96356, 0x12606060, 0xF0372D2D, 0xF0494040,
                    0xDD160D0D, 0xF0554C4C, 0xFFC04838, 0xFFD6887E, 0xFFE8D2C8, 0xFF978882,
                    0xFF7AA888, 0xFFB24230, 0xFFDC6A46, 0xFFCCA040, 0xFF180E0E, 0x33C04838,
                    0xFF363024, 0xFF2E281E, 0xFF332828, 0xFF4F403E, 0x55C04838, 0x66120A0A,
                    0xCCC04838, 0xEED37F74, 0x1AFFFFFF, 0x440D0707, 0x66CD6D60, 0xC8C04838,
                    0xD81C1010, 0xD02E2323, 0x88863227, 0xC0372D2D, 0x5E1C1010, 0x90C04838,
                    0x521C1010, 0x442E2323, 0x8C372D2D, 0x381C1010,
                    UiClimate.Material.SEAL));

    private final String id;
    private final UiClimate.Palette quietStudy;
    private final UiClimate.Palette fieldNotes;
    private final UiClimate.Palette ledgerHall;
    private final UiClimate.Palette omenRed;

    private static volatile UiTheme active = INKSCROLL;

    UiTheme(String id, UiClimate.Palette quietStudy, UiClimate.Palette fieldNotes,
            UiClimate.Palette ledgerHall, UiClimate.Palette omenRed) {
        this.id = id;
        this.quietStudy = quietStudy;
        this.fieldNotes = fieldNotes;
        this.ledgerHall = ledgerHall;
        this.omenRed = omenRed;
    }

    public String id() {
        return id;
    }

    /** Translation key for the theme display name. */
    public String displayNameKey() {
        return "screen.seeking_immortals.ui_theme." + id;
    }

    /** Palette this theme uses for the given scene; INKSCROLL delegates to the scene baseline. */
    public UiClimate.Palette paletteFor(InkScene scene) {
        InkScene s = InkScene.safe(scene);
        if (quietStudy == null) {
            return s.basePalette();
        }
        return switch (s) {
            case QUIET_STUDY -> quietStudy;
            case FIELD_NOTES -> fieldNotes;
            case LEDGER_HALL -> ledgerHall;
            case OMEN_RED -> omenRed;
        };
    }

    public static UiTheme active() {
        return active;
    }

    /** Sets the active theme and rebinds every ImmortalUiSkin color alias. */
    public static void setActive(UiTheme theme) {
        active = theme == null ? INKSCROLL : theme;
        com.xunxian.seekingimmortals.client.ImmortalUiSkin.refreshPalette();
    }

    /** Cycle helper for the in-game switch button. */
    public UiTheme next() {
        UiTheme[] all = values();
        return all[(ordinal() + 1) % all.length];
    }

    /** Parses a persisted id; unknown/null falls back to INKSCROLL. */
    public static UiTheme byId(String id) {
        if (id != null) {
            for (UiTheme theme : values()) {
                if (theme.id.equalsIgnoreCase(id.trim())) {
                    return theme;
                }
            }
        }
        return INKSCROLL;
    }

    /**
     * Texture tile prefix under {@code textures/gui/ink/}; {@code null} means the
     * theme keeps the 云笈墨卷 baseline paper tiles. Non-null prefixes resolve to
     * {@code <prefix>_quiet|field|ledger|omen.png} (scripts/generate_ink_ui_textures.py).
     */
    public String texturePrefix() {
        return switch (this) {
            case INKSCROLL -> null;
            case NIGHT_STARCHART -> "night";
            case BRONZE_TRIPOD -> "bronze";
            case CAVE_INSCRIPTION -> "cave";
            case TALISMAN_PAPER -> "talisman";
            case INKWASH_LANDSCAPE -> "inkwash";
            case MYSTIC_VIAL -> "vial";
            case BLOOD_TRIAL -> "blood";
            case MAPLE_VALLEY -> "maple";
            case AZURE_SWORD -> "azure";
            case GOLD_BEETLE -> "beetle";
        };
    }
}
