package com.xunxian.seekingimmortals.visual;

import java.util.Locale;

/** Finite renderer primitives emitted by the authored visual compiler. */
public enum VisualPrimitive {
    AURA_BURST, SINGLE_PROJECTILE, GIANT_CLAW, GIANT_HAND, FIST_BARRAGE,
    SWORD_RAIN, PROJECTILE_SWARM, FALLING_BARRAGE, CLOUD_VORTEX, RUNE_ORBIT,
    ARRAY_RINGS, CHAIN_NET, CHAIN_LINKS, SPIRIT_AVATAR, SUMMON_GATE,
    SERPENT_DRAGON, EYE_GAZE, SOUND_WAVE, LOTUS_MANDALA, MOUNTAIN_METEOR,
    MIRROR_DISC, MIST_VEIL, FLAME_BIRD, BEAST_PHANTOM, SPATIAL_RIFT,
    ICE_PRISON, BLOOD_SEA, TREE_AVATAR, SCRIPTURE_GLYPH, MAGNETIC_FIELD,
    LIGHTNING_STORM, WHEEL_DISC, SPEAR_SPIKE, WING_FAN, INSECT_SWARM,
    TIDAL_WAVE, ORB_PROJECTILE, GROUND_FIELD, SPHERE_FIELD, SEAL_CAGE, BARRIER_PLANE,
    BODY_AURA, BODY_SHELL, AFTERIMAGE_PATH, LAYERED_AFTERIMAGES,
    BEAM_LANCE, CHANNEL_STREAM, BLADE_ARC, IMPACT_ARCS, RISING_MOTES,
    CLEANSING_RING, BURNING_TALISMAN,
    // semantic_layers_v3 figure silhouettes (layer-scoped dispatch only).
    CAULDRON_VESSEL, BELL_CHIME, GOURD_VESSEL, LIGHT_CURTAIN,
    HALO_RING, BANNER_STREAMER, SEAL_STAMP, BRIDGE_ARC,
    // 0.2.200 deeper figure silhouettes
    FLYING_SWORD, GIANT_SWORD, FORMATION_BANNER, PAGODA_TOWER, BLOOD_THREAD, JADE_SLIP, FIRE_PLUME,
    GHOST_HEAD, SHIELD_PLATE, FLYING_BLADE, GIANT_AXE,
    RITUAL_BOWL, MAGIC_RULER, GIANT_HAMMER,
    MAGIC_STAFF, RITUAL_LAMP, SPIRIT_QIN, RITUAL_COFFIN, TALISMAN_BRUSH,
    MAGIC_FAN, ALCHEMY_FURNACE, MAGIC_SCROLL, FORMATION_DISC, SPIKED_CLUB,
    COMMAND_TOKEN, MAGIC_SCISSORS, MAGIC_BRICK, MAGIC_UMBRELLA, MAGIC_BOW,
    MAGIC_RUYI, MAGIC_HOOK, MAGIC_WHIP, MAGIC_ROPE, MAGIC_BOAT, MAGIC_CHARIOT, MAGIC_HALL,
    FORTRESS_WALL, MAGIC_GATE, MAGIC_SCREEN, MAGIC_PAGE,
    RITUAL_ALTAR,
    PUPPET_FIGURE, MAGIC_VAJRA, MAGIC_BOX, MAGIC_NEEDLE, SPIKED_SHIELD,
    MAGIC_GONG, MAGIC_MASK, MAGIC_CLOTH, RUNE_PILLAR, SPIRIT_ARMOR,
    CONFUCIAN_SAGE, FORMATION_ROD, RUNE_STELE;

    public static VisualPrimitive parse(String value) {
        if (value == null || value.isBlank()) {
            throw new IllegalArgumentException("blank visual primitive");
        }
        return valueOf(value.trim().replace('-', '_').replace(' ', '_').toUpperCase(Locale.ROOT));
    }

    public String id() {
        return name().toLowerCase(Locale.ROOT);
    }
}
